#!/usr/bin/env python3
"""Push an epic branch and open its PR, authenticating to GitHub with a token.

Args: <epic> [<base_branch>=main]

Best-effort throughout: writes only to stderr and always exits 0 (this must
never halt open-pr.py, whose JSON on stdout gates the CI/merge loop). Leaves
the branch unpushed / PR unopened for a manual follow-up on any failure.
"""
from __future__ import annotations

import logging
import os
import subprocess
import sys
from pathlib import Path

from workhorse.scriptutil import find_repo_root

from lib import ghutil

logger = logging.getLogger(__name__)

QUEUE_PATH = "docs/epics/index.md"


def main() -> None:
    logging.basicConfig(stream=sys.stderr, level=logging.INFO, format="%(name)s %(levelname)s: %(message)s")
    epic = sys.argv[1] if len(sys.argv) > 1 else ""
    base = sys.argv[2] if len(sys.argv) > 2 else "main"
    if not epic:
        return
    br = f"feat/{epic}"

    root = find_repo_root()
    scripts_dir = Path(__file__).resolve().parent

    if not ghutil.branch_exists(br, root):
        logger.info("no branch %s to PR", br)
        return

    # Commit the queue prune onto the epic branch before pushing, best-effort.
    subprocess.run(["git", "add", "--", QUEUE_PATH], cwd=str(root), stdout=sys.stderr, stderr=sys.stderr, text=True, check=False)
    diff = subprocess.run(
        ["git", "diff", "--cached", "--quiet", "--", QUEUE_PATH],
        cwd=str(root), capture_output=True, text=True, check=False,
    )
    if diff.returncode != 0:
        commit = subprocess.run(
            ["git", "commit", "-m", f"{epic}: prune completed epic from queue", "--", QUEUE_PATH],
            cwd=str(root), stdout=sys.stderr, stderr=sys.stderr, text=True, check=False,
        )
        if commit.returncode == 0:
            logger.info("committed index.md prune onto %s", br)
        else:
            logger.info("could not commit index.md onto %s", br)

    token = ghutil.resolve_gh_token(scripts_dir)
    if not token:
        logger.info("no GitHub token (set workflow.githubTokenEnv in agents.yml) — leaving %s for a manual PR", br)
        return
    if not ghutil.origin_url(root):
        logger.info("no 'origin' remote — leaving %s for a manual PR", br)
        return
    if not ghutil.gh_available():
        logger.info("gh CLI not found — leaving %s for a manual PR", br)
        return

    env = {**os.environ, "GH_TOKEN": token}

    subprocess.run(
        [sys.executable, str(scripts_dir / "push-epic.py"), br],
        cwd=str(root), env=env, stdout=sys.stderr, stderr=sys.stderr, text=True, check=False,
    )

    if ghutil.run(["gh", "pr", "view", br, "--json", "number"], root, env=env).returncode == 0:
        logger.info("PR already open for %s", br)
        return

    create = ghutil.run(
        [
            "gh", "pr", "create",
            "--base", base, "--head", br,
            "--title", f"Epic: {epic}",
            "--body",
            f"Automated epic PR for `{epic}`, generated by the coder workflow. "
            "One PR per epic; one commit per completed story.",
        ],
        root, env=env, timeout=60, echo=True,
    )
    if create.returncode != 0:
        logger.info("gh pr create failed for %s", br)


if __name__ == "__main__":
    main()
