# Agent launcher — farrier adapter regeneration (generated).
#
# Generated by farrier (the prompt-library installer). Do not edit by hand;
# re-run `make agent-install` to regenerate. Include it from a root Makefile:
#
#   include .agents/agents.mk
#
# Usage:
#   make agent-install             # regenerate the agent adapters from the library
#   make agent-check               # verify adapters are up to date (no writes)
#
# No containerized run targets: no workflow distribution is installed here. Install
# one (`uv tool install workhorse-workflows`) and re-run `make agent-install`; a
# target appears per discovered workflow. To run one directly, without a container:
#
#   workhorse-<name> run --dry-run     # static preflight, drives nothing
#   workhorse-<name> run

AGENTS_DIR     ?= $(shell farrier config show library_dir)
# Public stablemate checkout (holds the farrier installer source). Needed only
# for SRC=1 local-source runs.
STABLEMATE_DIR ?= $(shell farrier config show stablemate_dir)

# farrier regenerates these adapters from the prompt library. Default uses the
# installed farrier binary. SRC=1 runs the local source under $(STABLEMATE_DIR)/farrier.
# The library CONTENT is located via `farrier config set-library`; when a
# vigilant-octo checkout exists at $(AGENTS_DIR) we pass --library explicitly.
ifeq ($(SRC),1)
FARRIER ?= uv run --project $(STABLEMATE_DIR)/farrier farrier
endif
FARRIER ?= farrier
FARRIER_LIB_ARG := $(if $(wildcard $(AGENTS_DIR)/library),--library "$(AGENTS_DIR)",)

.DEFAULT_GOAL := help

.PHONY: help agent-install agent-check

help: ## Show available targets
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN{FS=":.*?## "}{printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

agent-install: ## Regenerate the agent adapters/skills from the prompt library
	$(FARRIER) --repo "$(CURDIR)" $(FARRIER_LIB_ARG)

agent-check: ## Verify generated agent adapters are up to date (no writes)
	@$(FARRIER) --repo "$(CURDIR)" --check $(FARRIER_LIB_ARG) \
		&& echo "✓ agent files are up to date" \
		|| { echo "↑ files above would be rewritten by 'make agent-install'"; exit 1; }
