"""What ``--check`` says when a generated file no longer matches its source.

The comparison itself is cheap and has always been right; what it said was
``changed: AGENTS.md``, which names neither the file to edit instead nor the fact
that re-rendering is the fix. An agent reading that has two plausible next moves and
both are wrong — revert its own work, or delete whatever stopped it. So the report
answers three questions in the order they get asked: what drifted, which library file
it is a copy of, and where the change belongs.

Provenance is resolved from the *expected* text, never the worktree's. A drifted file
is one somebody edited, and its banner or front matter is exactly as editable as the
body — reading the source list off the copy under suspicion would let the edit choose
where it gets reported.
"""

from __future__ import annotations

from dataclasses import dataclass

from farrier.frontmatter import banner_sources, frontmatter_metadata


@dataclass(frozen=True)
class Drifted:
    """One generated file whose worktree copy differs from a fresh render.

    Carries the expected text as well as the actual, because provenance is read off
    the expected side and attribution needs both.
    """

    rel: str
    content: str
    expected: str
    actual: str

#: How the operator re-renders. Named rather than spelled as `farrier install` because
#: the Makefile include is what every farrier-installed repo has, and the bare command
#: needs the library flags this one already carries.
REGENERATE = "make agent-install"


def sources_for(content: str, expected: str) -> list[str]:
    """The library files *content* is generated from, in render order.

    Three provenance carriers, in descending authority: the aggregate's own record
    (set by the renderer, which is the only thing that knows the mapping), the
    ``metadata.source`` a generated skill or command stamps into its front matter,
    and the HTML banner a bundled reference carries. Empty when a file has none of
    them — a launcher fragment or a scaffold has no single editable original.
    """
    recorded = getattr(content, "sources", ())
    if recorded:
        return list(recorded)
    stamped = frontmatter_metadata(expected).get("source")
    if stamped:
        return [stamped]
    return banner_sources(expected)


def attribute(content: str, actual: str) -> set[str]:
    """Which of an aggregate's sources contain the drift.

    An aggregated AGENTS.md is several library files joined end to end, and its halves
    can sit hundreds of lines apart — "put this back upstream" is not actionable until
    it says *which* upstream. The renderer records each source's rendered part, so a
    part that no longer appears verbatim in the worktree copy is the one that was
    edited. Returns an empty set when the file records no parts, or when the edit
    perturbed all of them (a reflow, a re-indent), and the caller falls back to naming
    every source rather than guessing at one.
    """
    parts = getattr(content, "parts", ())
    if not parts:
        return set()
    drifted = {rel for rel, part in parts if part and part not in actual}
    return set() if len(drifted) == len(parts) else drifted


def _sources_clause(sources: list[str], drifted: set[str]) -> str:
    if not sources:
        return "  farrier generates this file; it has no single editable source."
    if len(sources) == 1:
        return f"  It is generated from {sources[0]}."
    listed = "\n".join(
        f"    - {rel}" + ("  <- the drift is in this one" if rel in drifted else "")
        for rel in sources
    )
    return "  It is generated from these library files, in render order:\n" + listed


def changed_report(rel: str, sources: list[str], drifted: set[str]) -> str:
    """The block printed under one ``changed:`` line."""
    return "\n".join(
        [
            f"  {rel} has drifted from the generated source"
            + ("s" if len(sources) > 1 else "")
            + ".",
            _sources_clause(sources, drifted),
            "  Put the update in the upstream file"
            + ("s" if len(sources) > 1 else "")
            + f" above, then re-render with `{REGENERATE}`.",
            f"  An edit made in {rel} itself is not kept — the next render",
            "  overwrites it, and nothing reports the loss.",
        ]
    )


def missing_report(rel: str) -> str:
    return (
        f"  {rel} is generated but absent from the working tree.\n"
        f"  Run `{REGENERATE}` to write it."
    )


def extra_report(rel: str) -> str:
    return (
        f"  {rel} is not generated by the current agents.yml — a selection was\n"
        "  removed or renamed and left this copy behind. Delete it, or restore\n"
        "  the entry in agents.yml that used to generate it."
    )


def footer() -> str:
    """Why the operator may be looking at a clean `git status` and a failing check."""
    return (
        "The comparison is against the working tree, not the index, so an unstaged\n"
        "edit counts. `farrier source <file>` prints the editable path for any one\n"
        "of them."
    )


def report(
    missing: list[str],
    changed: list[Drifted],
    extra: list[str],
) -> str:
    """The whole ``--check`` failure, ready to print."""
    blocks: list[str] = []
    for rel in missing:
        blocks.append(f"missing: {rel}\n{missing_report(rel)}")
    for record in changed:
        sources = sources_for(record.content, record.expected)
        drifted = attribute(record.content, record.actual)
        blocks.append(
            f"changed: {record.rel}\n{changed_report(record.rel, sources, drifted)}"
        )
    for rel in extra:
        blocks.append(f"extra: {rel}\n{extra_report(rel)}")
    return "\n\n".join([*blocks, footer()])
