"""YAML front-matter and metadata parsing for library and generated files.

Reading config YAML, splitting/parsing front matter, and pulling provenance out of
a generated file's banner or ``metadata`` block. Pure parsing — no ``Source``.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml


def read_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"Missing config: {path}")
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"Config must be a YAML mapping: {path}")
    return data


def banner_sources(text: str) -> list[str]:
    """Library source paths listed in a generated file's leading HTML banner.

    Last-resort provenance for `farrier source`: the banner is a snapshot from
    generation time, so it is only consulted when no agents.yml is found above
    the file — the live localInstructions mapping always wins when available.
    Returns [] when the file does not start with a farrier banner.
    """
    match = re.match(r"\A<!--\n(?P<banner>.*?)\n-->", text, flags=re.DOTALL)
    if not match or "generated by farrier" not in match.group("banner"):
        return []
    return re.findall(r"^\s+(library/\S+)$", match.group("banner"), flags=re.MULTILINE)


def mapping_skill_names(mapping: dict[str, Any]) -> list[str]:
    """The installed skill names a localInstructions mapping selects.

    A mapping names a single skill (`skill: foo`) or several (`skills: [foo,
    bar]`); multiple skills are aggregated into one generated file, separated by
    a `---` markdown rule, in listed order.
    """
    if mapping.get("skills"):
        return [str(name) for name in mapping["skills"]]
    return [str(mapping["skill"])]


def split_front_matter(content: str) -> tuple[dict[str, str], str]:
    match = re.match(
        r"\A---\n(?P<header>.*?)\n---\n\n?(?P<body>.*)\Z",
        content,
        flags=re.DOTALL,
    )
    if not match:
        return {}, content

    header: dict[str, str] = {}
    for line in match.group("header").splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        header[key.strip()] = value.strip().strip('"').strip("'")
    return header, match.group("body")


def frontmatter_metadata(text: str) -> dict[str, Any]:
    """Parse a generated file's YAML front matter and return its `metadata` mapping.

    Uses a real YAML parse (not the flat line-splitter in ``split_front_matter``)
    because the provenance is a *nested* block. Returns ``{}`` for a file with no
    front matter, no `metadata:` block, or malformed YAML.
    """
    match = re.match(r"\A---\n(?P<header>.*?)\n---\n", text, flags=re.DOTALL)
    if not match:
        return {}
    try:
        data = yaml.safe_load(match.group("header")) or {}
    except yaml.YAMLError:
        return {}
    meta = data.get("metadata") if isinstance(data, dict) else None
    return meta if isinstance(meta, dict) else {}


def first_heading(body: str, fallback: str) -> str:
    for line in body.splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return fallback
