"""YAML front-matter and metadata parsing for library and generated files.

Reading config YAML, splitting/parsing front matter, and pulling provenance out of
a generated file's banner or ``metadata`` block. Pure parsing — no ``Source``.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

import yaml


def read_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"Missing config: {path}")
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"Config must be a YAML mapping: {path}")
    return data


def banner_sources(text: str) -> list[str]:
    """Library source paths listed in a generated file's leading HTML banner.

    Last-resort provenance for `farrier source`: the banner is a snapshot from
    generation time, so it is only consulted when no agents.yml is found above
    the file — the live localInstructions mapping always wins when available.
    Returns [] when the file does not start with a farrier banner.
    """
    match = re.match(r"\A<!--\n(?P<banner>.*?)\n-->", text, flags=re.DOTALL)
    if not match or "generated by farrier" not in match.group("banner"):
        return []
    return re.findall(r"^\s+(library/\S+)$", match.group("banner"), flags=re.MULTILINE)


def mapping_skill_names(mapping: dict[str, Any]) -> list[str]:
    """The installed skill names a localInstructions mapping selects.

    A mapping names a single skill (`skill: foo`) or several (`skills: [foo,
    bar]`); multiple skills are aggregated into one generated file, separated by
    a `---` markdown rule, in listed order.
    """
    if mapping.get("skills"):
        return [str(name) for name in mapping["skills"]]
    return [str(mapping["skill"])]


def split_front_matter(content: str) -> tuple[dict[str, str], str]:
    match = re.match(
        r"\A---\n(?P<header>.*?)\n---\n\n?(?P<body>.*)\Z",
        content,
        flags=re.DOTALL,
    )
    if not match:
        return {}, content

    header: dict[str, str] = {}
    for line in match.group("header").splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        header[key.strip()] = value.strip().strip('"').strip("'")
    return header, match.group("body")


def normalize_tags(value: Any) -> list[str]:
    """The tag list a `tags:` value denotes — lowercased, stripped, order-preserving.

    A tag is a *query key*: prompts ask for a capability with
    ``find_by_tags('web', 'tests')`` instead of naming the skills that provide it. So
    `Web` failing to match `web` would be a silent miss rather than an error, and the
    normalization happens once, here, rather than at each comparison.

    A bare string is split on commas — the form an author types when they forget it is
    a list — and anything else yields no tags at all.
    """
    if isinstance(value, str):
        items: list[Any] = value.split(",")
    elif isinstance(value, (list, tuple)):
        items = list(value)
    else:
        return []
    tags: list[str] = []
    for item in items:
        tag = str(item).strip().strip('"').strip("'").lower()
        if tag and tag not in tags:
            tags.append(tag)
    return tags


def frontmatter_tags(text: str) -> list[str]:
    """The `tags:` a file's front matter declares, normalized by :func:`normalize_tags`.

    A real YAML parse rather than ``split_front_matter``'s line splitter, because both
    spellings an author reaches for have to work: the flow list ``tags: [go, testing]``
    and the block list of ``- `` items under ``tags:``. The line splitter sees the
    first as an unparsed string and the second as empty, and a tag that silently does
    not exist is the one failure mode a tag query cannot report.

    Returns ``[]`` for a file with no front matter, no `tags:`, or malformed YAML.
    """
    match = re.match(r"\A---\n(?P<header>.*?)\n---\n", text, flags=re.DOTALL)
    if not match:
        return []
    try:
        data = yaml.safe_load(match.group("header")) or {}
    except yaml.YAMLError:
        return []
    return normalize_tags(data.get("tags") if isinstance(data, dict) else None)


def frontmatter_metadata(text: str) -> dict[str, Any]:
    """Parse a generated file's YAML front matter and return its `metadata` mapping.

    Uses a real YAML parse (not the flat line-splitter in ``split_front_matter``)
    because the provenance is a *nested* block. Returns ``{}`` for a file with no
    front matter, no `metadata:` block, or malformed YAML.
    """
    match = re.match(r"\A---\n(?P<header>.*?)\n---\n", text, flags=re.DOTALL)
    if not match:
        return {}
    try:
        data = yaml.safe_load(match.group("header")) or {}
    except yaml.YAMLError:
        return {}
    meta = data.get("metadata") if isinstance(data, dict) else None
    return meta if isinstance(meta, dict) else {}


def first_heading(body: str, fallback: str) -> str:
    for line in body.splitlines():
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return fallback
