"""YAML front-matter and metadata parsing for library and generated files.

Reading config YAML, splitting/parsing front matter, and pulling provenance out of
a generated file's banner or ``metadata`` block. Pure parsing — no ``Source``.

Everything here goes through a parser: ``markdown-it-py`` + ``front_matter_plugin`` finds
the fence, ``yaml`` reads what is inside it. farrier keeps its own module rather than
importing ``ostler.markdown`` because it needs frontmatter and never the section tree, and
``farrier -> ostler`` is a dependency edge the workspace deliberately does not draw — but
it is the *same* parser underneath, so the two cannot disagree about where a fence ends.
See the ``stablemate-structured-parsing`` skill.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml
from markdown_it import MarkdownIt
from mdit_py_plugins.front_matter import front_matter_plugin

_MD = MarkdownIt("commonmark").use(front_matter_plugin)


def _tokens(text: str):
    """Block tokens for *text*, with line endings normalized the way the parser sees them."""
    return _MD.parse(text.replace("\r\n", "\n").replace("\r", "\n"))


def _front_matter(text: str) -> dict[str, Any]:
    """The parsed front-matter mapping — ``{}`` for no front matter or malformed YAML.

    One reader for all three public accessors. Three separate regexes used to fence off
    the same block with three slightly different patterns; a document any one of them
    disagreed about was read differently depending on which entry point you came through.
    """
    tokens = _tokens(text)
    if not tokens or tokens[0].type != "front_matter":
        return {}
    try:
        # The token drops the block's final newline; a folded scalar's trailing-newline
        # semantics depend on it, so give YAML the block as it was written.
        data = yaml.safe_load(tokens[0].content + "\n") or {}
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def frontmatter_mapping(text: str) -> dict[str, Any]:
    """The whole parsed front matter of a markdown source — ``{}`` when there is none.

    The three accessors below each read one key off it. This one is for readers that
    need a key farrier has no dedicated accessor for (``hooks:``), and it keeps them on
    the same lenient parse: a source whose fence does not parse is one farrier renders
    without front matter, so a reader that raised where the renderer shrugs would
    disagree with what actually got installed.
    """
    return _front_matter(text)


def read_yaml(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise SystemExit(f"Missing config: {path}")
    with path.open(encoding="utf-8") as handle:
        data = yaml.safe_load(handle) or {}
    if not isinstance(data, dict):
        raise SystemExit(f"Config must be a YAML mapping: {path}")
    return data


def banner_sources(text: str) -> list[str]:
    """Library source paths listed in a generated file's leading HTML banner.

    Last-resort provenance for `farrier source`: the banner is a snapshot from
    generation time, so it is only consulted when no agents.yml is found above
    the file — the live localInstructions mapping always wins when available.
    Returns [] when the file does not start with a farrier banner.
    """
    tokens = _tokens(text)
    if not tokens or tokens[0].type != "html_block":
        return []
    banner = tokens[0].content
    if not banner.startswith("<!--") or "generated by farrier" not in banner:
        return []
    # Inside our own banner the source list is one indented path per line — a list, with
    # no grammar to parse. What the parser settles is where the banner *ends*, so a
    # `library/…` path further down the document is not mistaken for provenance.
    out: list[str] = []
    for line in banner.splitlines():
        fields = line.split()
        if line[:1].isspace() and len(fields) == 1 and fields[0].startswith("library/"):
            out.append(fields[0])
    return out


#: The files a localInstructions mapping generates. AGENTS.md carries the aggregated
#: text — every harness reads that name natively — and CLAUDE.md is a pointer to it,
#: written only when the claude adapter is on. `farrier source` resolves either back
#: through agents.yml by its name, so the set is closed.
LOCAL_INSTRUCTION_FILES = ("AGENTS.md", "CLAUDE.md")


def mapping_skill_names(mapping: dict[str, Any]) -> list[str]:
    """The installed skill names a localInstructions mapping selects.

    A mapping names a single skill (`skill: foo`) or several (`skills: [foo,
    bar]`); multiple skills are aggregated into one generated file, separated by
    a `---` markdown rule, in listed order. Empty when the mapping selects
    prompts only.
    """
    if mapping.get("skills"):
        return [str(name) for name in mapping["skills"]]
    if mapping.get("skill"):
        return [str(mapping["skill"])]
    return []


def mapping_policy_names(mapping: dict[str, Any]) -> list[str]:
    """The policy names a localInstructions mapping selects.

    A policy is library text that exists *only* here. It is never installed as a skill,
    so it costs nothing in the skill index the agent carries every turn — which is the
    whole point: a standing rule aggregated into AGENTS.md is already resident, and an
    index entry advertising it is a second charge for text nobody can usefully invoke.

    Policies are aggregated first, ahead of the mapping's skills and prompts: standing
    rules above procedures. Empty when the mapping selects no policies.
    """
    if mapping.get("policies"):
        return [str(name) for name in mapping["policies"]]
    if mapping.get("policy"):
        return [str(mapping["policy"])]
    return []


def mapping_prompt_names(mapping: dict[str, Any]) -> list[str]:
    """The installed prompt names a localInstructions mapping selects.

    The prompt analogue of ``mapping_skill_names``: a procedure a repo wants
    always loaded rather than invoked as a slash command is written once as a
    library prompt and aggregated here, after the mapping's skills, so the same
    text is not maintained per repo. Empty when the mapping selects skills only.
    """
    if mapping.get("prompts"):
        return [str(name) for name in mapping["prompts"]]
    if mapping.get("prompt"):
        return [str(mapping["prompt"])]
    return []


#: Legacy spellings of `includeReadme`, from when the key chose the *mechanism*
#: (copy the body in, or reference it with Claude's `@` directive). The mechanism
#: is no longer the author's to pick — it follows the file being written — so the
#: key is a boolean now, and the old words map onto it.
_README_ALIASES = {"inline": True, "import": True, "none": False}


def mapping_include_readme(mapping: dict[str, Any]) -> bool:
    """Whether a localInstructions mapping folds in the sibling README.md.

    True by default: a directory's README is usually the orientation an agent
    working there wants. How it gets in is decided per generated file, not here —
    CLAUDE.md references it with `@README.md`, and AGENTS.md, which harnesses
    without an import directive read, gets the body copied.
    """
    value = mapping.get("includeReadme", True)
    if isinstance(value, bool):
        return value
    key = str(value)
    if key not in _README_ALIASES:
        raise SystemExit(
            f"localInstructions.includeReadme must be true or false "
            f"(got {value!r}; the {'/'.join(_README_ALIASES)} spellings are the "
            "old mechanism-picking form and still work)"
        )
    return _README_ALIASES[key]


def _as_text(value: Any) -> str:
    """A header value as the single string the renderer templates and re-quotes.

    Callers of ``split_front_matter`` render every value through Jinja and re-emit it with
    ``yaml_quote``, so this view is flat by contract. Non-scalars come back in flow style —
    the spelling the author wrote — rather than as a Python ``repr``.
    """
    if value is None:
        return ""
    if isinstance(value, str):
        return value
    if isinstance(value, (list, dict)):
        return yaml.safe_dump(value, default_flow_style=True, allow_unicode=True).strip()
    return str(value)


def split_front_matter(content: str) -> tuple[dict[str, str], str]:
    """``({key: value}, body)`` — front matter as a flat string map, plus the rest.

    The values come from ``yaml.safe_load``, not from a ``line.split(":", 1)`` loop. That
    loop could not read a folded (``description: >``) or quoted-colon value, and treated
    the indented lines of a nested ``metadata:`` block as top-level keys of their own.
    """
    tokens = _tokens(content)
    # A `front_matter` token always carries a line map; the check is what says so to a
    # reader of `tokens[0].map` two lines down, and a token stream without one has no
    # fence this function can honour anyway.
    if not tokens or tokens[0].type != "front_matter" or not tokens[0].map:
        return {}, content
    body = "\n".join(
        content.replace("\r\n", "\n").replace("\r", "\n").split("\n")[tokens[0].map[1]:]
    )
    return ({key: _as_text(value) for key, value in _front_matter(content).items()},
            body.removeprefix("\n"))  # one blank line after the fence is separator, not body


def normalize_tags(value: Any) -> list[str]:
    """The tag list a `tags:` value denotes — lowercased, stripped, order-preserving.

    A tag is a *query key*: prompts ask for a capability with
    ``find_by_tags('web', 'tests')`` instead of naming the skills that provide it. So
    `Web` failing to match `web` would be a silent miss rather than an error, and the
    normalization happens once, here, rather than at each comparison.

    A bare string is split on commas — the form an author types when they forget it is
    a list — and anything else yields no tags at all.
    """
    if isinstance(value, str):
        items: list[Any] = value.split(",")
    elif isinstance(value, (list, tuple)):
        items = list(value)
    else:
        return []
    tags: list[str] = []
    for item in items:
        tag = str(item).strip().strip('"').strip("'").lower()
        if tag and tag not in tags:
            tags.append(tag)
    return tags


def frontmatter_tags(text: str) -> list[str]:
    """The `tags:` a file's front matter declares, normalized by :func:`normalize_tags`.

    A real YAML parse rather than ``split_front_matter``'s line splitter, because both
    spellings an author reaches for have to work: the flow list ``tags: [go, testing]``
    and the block list of ``- `` items under ``tags:``. The line splitter sees the
    first as an unparsed string and the second as empty, and a tag that silently does
    not exist is the one failure mode a tag query cannot report.

    Returns ``[]`` for a file with no front matter, no `tags:`, or malformed YAML.
    """
    return normalize_tags(_front_matter(text).get("tags"))


def frontmatter_metadata(text: str) -> dict[str, Any]:
    """Parse a generated file's YAML front matter and return its `metadata` mapping.

    Uses a real YAML parse (not the flat line-splitter in ``split_front_matter``)
    because the provenance is a *nested* block. Returns ``{}`` for a file with no
    front matter, no `metadata:` block, or malformed YAML.
    """
    meta = _front_matter(text).get("metadata")
    return meta if isinstance(meta, dict) else {}


def first_heading(body: str, fallback: str) -> str:
    """The body's first level-1 heading, or *fallback*.

    Read off the token stream, so a ``# `` line inside a fenced block is a code sample
    rather than the document's title — which is exactly what a skill demonstrating
    markdown puts in its first fence.
    """
    tokens = _tokens(body)
    for i, tok in enumerate(tokens):
        if tok.type == "heading_open" and tok.tag == "h1":
            return tokens[i + 1].content.strip() if i + 1 < len(tokens) else fallback
    return fallback


def front_matter_end(content: str) -> int:
    """The line index where the document proper begins — ``0`` when there is no fence.

    Lets a caller splice a banner *after* a source's own front matter instead of above
    it, which would push the fence off line 1 and turn parsed metadata into prose.
    """
    tokens = _tokens(content)
    if not tokens or tokens[0].type != "front_matter" or not tokens[0].map:
        return 0
    return tokens[0].map[1]
