"""Generation of the ``.agents/`` launcher scaffolding.

The generated make launcher (agents.mk) and the local-run compose override, plus
the path constants and defaults naming what they write.
"""
from __future__ import annotations

from typing import Any

from farrier.naming import kebab


# Launcher scaffolding generated when >= 1 workflow is installed. These are
# always-owned generated files (registered for --check and cleanup). The thin
# root Makefile is special-cased: it is only written when no root Makefile
# already exists, and is never removed by cleanup (a user may hand-author it).
LAUNCHER_AGENTS_MK = ".agents/agents.mk"
LAUNCHER_COMPOSE = ".agents/local.compose.yaml"
LAUNCHER_CONTEXT_MANIFEST = ".agents/agents-context.json"
# Per-assistant context manifests (one per enabled agent) so a Codex/Copilot run
# resolves instruction_ref to its own adapters. Selected by AGENT_CLI at run time;
# the generic LAUNCHER_CONTEXT_MANIFEST above stays the primary assistant's copy.
LAUNCHER_CONTEXT_MANIFEST_FMT = ".agents/agents-context.{}.json"
LAUNCHER_ROOT_MAKEFILE = "Makefile"
# Default relative path from the target repo to the vigilant-octo agents dir
# (the prompt-library *content*). Overridable per-repo via agents.yml:
# workflow.agentsDir.
DEFAULT_AGENTS_DIR = "$(abspath $(CURDIR)/../vigilant-octo/agents)"
# Default relative path to the public `stablemate` checkout (holds the workhorse
# runtime source and the farrier installer source — needed only for Docker runs
# and SRC=1 local-source runs). Overridable via the STABLEMATE_DIR make var.
DEFAULT_STABLEMATE_DIR = "$(abspath $(CURDIR)/../stablemate)"


def render_agents_mk(workflows: list[str], meta: dict[str, Any]) -> str:
    """Generic, workflow-name-parameterized make launcher (.agents/agents.mk).

    ALWAYS generated: its regeneration targets (`agent-install`/`agent-check`)
    are useful for a skills/prompts-only repo too, and a root Makefile can then
    `include` it unconditionally. The workflow-run configuration and targets
    (`agent-run`, `agent-native`, `agent-build`, …) are only emitted when >= 1
    workflow is installed.

    Mirrors the assembler Makefile (COMPOSE = base + override layering, ENVV with
    WORKFLOW_DIR / REPO_SRC / REPO_BRANCH / REPO_NAME, native via uv run) but uses
    NEUTRAL `agent-*` target names and a `WF` variable defaulting to the first
    installed workflow. No 'hrnet' / 'research' / 'assembler' hardcoding.
    """
    has_wf = bool(workflows)
    default_wf = workflows[0] if has_wf else ""
    workflow_list = " ".join(workflows) if has_wf else "(none — skills/prompts only)"

    if has_wf:
        usage = f"""#   make agent-run                 # Docker + local clone (default WF={default_wf})
#   make agent-run WF=<name>       # pick another installed workflow
#   make agent-native              # native (no Docker) on THIS working tree (foreground)
#   make agent-native AGENT_CLI=copilot   # run on Codex/Copilot instead of Claude (native only)
#   make agent-native-bg           # native, detached — saves pid; watch with agent-logs
#   make agent-native SRC=1        # native from local stablemate source ($(LOCAL_WORKER))
#   make agent-logs                # follow the current run log (.agents/runs/<WF>.log)
#   make agent-stop                # stop a detached native run (agent-native-bg)
#   make agent-build               # rebuild image + run
#   make agent-hello               # smoke-test with hello-world
#   make agent-container-logs      # follow the Docker container logs
#   make agent-down                # stop containers (keep volumes)
#   make agent-reseed-auth         # clear auth + re-seed credentials
#   make agent-clean               # wipe ALL volumes
#   make agent-artifacts           # copy run artifacts into ./.agents/runs
#   make agent-install             # regenerate these adapters from the library
#   make agent-check               # verify adapters are up to date (no writes)"""
    else:
        usage = """#   make agent-install             # regenerate the agent adapters from the library
#   make agent-check               # verify adapters are up to date (no writes)
#
# No workflows are installed in this repo, so the workflow-run targets
# (agent-run / agent-native / agent-build / …) are omitted. Add a workflow to
# this repo's agents.yml and re-run `make agent-install` to get them."""

    header = f"""# Agent launcher — workhorse quick start (generated).
#
# Generated by farrier (the prompt-library installer). Do not edit by hand;
# re-run `make agent-install` to regenerate. Include it from a root Makefile:
#
#   include .agents/agents.mk
#
# Installed workflows: {workflow_list}
#
# Usage:
{usage}
"""

    core = """
AGENTS_DIR     ?= $(shell farrier config show library_dir)
# Public stablemate checkout (workhorse runtime + farrier installer source).
# Needed only for Docker runs and SRC=1 local-source runs.
STABLEMATE_DIR ?= $(shell farrier config show stablemate_dir)

# farrier regenerates these adapters from the prompt library. Default uses the
# installed farrier binary. SRC=1 runs the local source under $(STABLEMATE_DIR)/farrier.
# The library CONTENT is located via `farrier config set-library`; when a
# vigilant-octo checkout exists at $(AGENTS_DIR) we pass --library explicitly.
ifeq ($(SRC),1)
FARRIER ?= uv run --project $(STABLEMATE_DIR)/farrier farrier
endif
FARRIER ?= farrier
FARRIER_LIB_ARG := $(if $(wildcard $(AGENTS_DIR)/library),--library "$(AGENTS_DIR)",)
"""

    wf_vars = ""
    wf_targets = ""
    phony_wf = ""
    if has_wf:
        placeholder = meta["repo_url"].startswith("REPLACE_ME")
        repo_url_line = (
            f"REPO_URL     ?= {meta['repo_url']}"
            if not placeholder
            else f"# REPO_URL: set me to the git remote (only used by GitHub-default runs,\n"
            f"# not the default local bind-mount clone). Auto-detection found no origin.\n"
            f"REPO_URL     ?= {meta['repo_url']}"
        )
        wf_vars = f"""
LOCAL_WORKER   := $(STABLEMATE_DIR)/workhorse
# WF selects which workflow to run; defaults to the first selected.
WF           ?= {default_wf}
# AGENT_CLI selects the agent backend: claude (default) | codex | copilot. Native
# runs check that this CLI is on PATH and forward it to workhorse; it also selects
# the per-assistant context manifest below.
AGENT_CLI    ?= claude
# Workflows run straight from the library — not copied into this repo. A workflow may
# live in the configured overlay OR in the base library wheel (site-packages), so the
# launcher does NOT build a path: it passes the workflow NAME and lets workhorse resolve
# it across the same layers farrier uses. Set WORKFLOW_DIR to pin a specific checkout.
WORKFLOW_DIR ?=
WORKFLOW_ARG := $(if $(WORKFLOW_DIR),$(WORKFLOW_DIR)/workflow.yaml,$(WF))
# Per-repo context manifest the library prompts render against (generated by
# `make agent-install`). Prefer the per-assistant manifest for $(AGENT_CLI) so a
# Codex/Copilot run resolves instruction_ref to its own adapters; fall back to the
# generic one. workhorse also auto-detects this from AGENT_REPO_DIR + AGENT_CLI.
CONTEXT_FILE ?= $(firstword $(wildcard $(CURDIR)/.agents/agents-context.$(AGENT_CLI).json) $(CURDIR)/.agents/agents-context.json)
REPO_NAME    ?= {meta["repo_name"]}
REPO_BRANCH  ?= {meta["branch"]}
{repo_url_line}
REPO_CONFIG  ?= $(CURDIR)/agents.yml
# Compose project name (default = first compose file's directory) → volume prefix.
PROJECT      ?= local-worker
# Native runs use the installed workhorse binary by default.
# SRC=1 runs workhorse from the local stablemate source checkout via uv.
# An explicit WORKHORSE=... overrides both.
ifeq ($(SRC),1)
WORKHORSE         ?= uv run --project $(LOCAL_WORKER) workhorse
WORKHORSE_VERSION ?= $(shell grep -m1 '^version' $(LOCAL_WORKER)/pyproject.toml 2>/dev/null | cut -d'"' -f2) (local source: $(LOCAL_WORKER))
endif
WORKHORSE         ?= workhorse
WORKHORSE_VERSION ?= $(shell workhorse --version 2>/dev/null || echo unknown) (installed)

# Optional run knobs forwarded to workhorse (native targets):
#   RUN_ID      names the stable run dir (<workflow>-<RUN_ID>); default "default".
#   PARAMS      inline JSON of workflow params, e.g. '{{"program":"hrnet-research"}}'.
#   PARAMS_FILE path to a JSON file of workflow params (same effect as PARAMS).
AGENT_ARGS := $(if $(RUN_ID),--run-id "$(RUN_ID)") $(if $(PARAMS),--params '$(PARAMS)') $(if $(PARAMS_FILE),--params-file "$(PARAMS_FILE)")

# Layer the local-run override on top of the generic worker compose. Each
# installed workflow is its own named service in local.compose.yaml (sharing one
# build via a YAML anchor) — $(WF) below selects which one runs.
COMPOSE := docker compose -p $(PROJECT) \\
\t-f $(LOCAL_WORKER)/compose.yaml \\
\t-f $(CURDIR)/.agents/local.compose.yaml
# The container runs as YOUR uid:gid, not a fixed `nobody`, so it can write into
# bind-mounted host paths you own (see the `user:` key in local.compose.yaml).
AGENT_UID    ?= $(shell id -u)
AGENT_GID    ?= $(shell id -g)
ENVV := PROJECT="$(PROJECT)" LOCAL_WORKER="$(LOCAL_WORKER)" STABLEMATE_DIR="$(STABLEMATE_DIR)" AGENTS_DIR="$(AGENTS_DIR)" REPO_SRC="$(CURDIR)" REPO_URL="$(REPO_URL)" REPO_CONFIG="$(REPO_CONFIG)" REPO_BRANCH="$(REPO_BRANCH)" REPO_NAME="$(REPO_NAME)" AGENT_UID="$(AGENT_UID)" AGENT_GID="$(AGENT_GID)"

# Per-workflow run log + pid (under the gitignored .agents/runs/).
RUNS_DIR     := $(CURDIR)/.agents/runs
LOG          := $(RUNS_DIR)/$(WF).log
PID          := $(RUNS_DIR)/$(WF).pid
"""
        phony_wf = " agent-run agent-native agent-native-bg agent-build agent-hello agent-logs agent-container-logs agent-stop agent-down agent-clean agent-reseed-auth agent-artifacts"
        wf_targets = """
agent-run: ## Run the selected workflow (Docker, local clone). Override with WF=<name>
\t@mkdir -p $(RUNS_DIR)
\t@bash -o pipefail -c '$(ENVV) $(COMPOSE) up --abort-on-container-exit --exit-code-from $(WF) $(WF) 2>&1 | tee "$(LOG)"'

agent-native: ## Run natively (no Docker, pipx) on THIS tree; logs tee'd to .agents/runs/$(WF).log
\t@mkdir -p $(RUNS_DIR)
\t@command -v $(AGENT_CLI) >/dev/null || { echo "error: '$(AGENT_CLI)' CLI not on PATH (set AGENT_CLI=claude|codex|copilot)"; exit 1; }
\t@echo "using workhorse-agent $(WORKHORSE_VERSION) (AGENT_CLI=$(AGENT_CLI))"
\tPYTHONUNBUFFERED=1 AGENT_CLI="$(AGENT_CLI)" AGENT_REPO_DIR="$(CURDIR)" $(WORKHORSE) \\
\t\t--workflow $(WORKFLOW_ARG) --context-file $(CONTEXT_FILE) --runs-dir $(RUNS_DIR) $(AGENT_ARGS) 2>&1 | tee $(LOG)

agent-native-bg: ## Detached native run; saves pid to .agents/runs/$(WF).pid (watch: make agent-logs)
\t@mkdir -p $(RUNS_DIR)
\t@command -v $(AGENT_CLI) >/dev/null || { echo "error: '$(AGENT_CLI)' CLI not on PATH (set AGENT_CLI=claude|codex|copilot)"; exit 1; }
\t@echo "using workhorse-agent $(WORKHORSE_VERSION) (AGENT_CLI=$(AGENT_CLI))"
\t@PYTHONUNBUFFERED=1 AGENT_CLI="$(AGENT_CLI)" AGENT_REPO_DIR="$(CURDIR)" nohup $(WORKHORSE) \\
\t\t--workflow $(WORKFLOW_ARG) --context-file $(CONTEXT_FILE) --runs-dir $(RUNS_DIR) $(AGENT_ARGS) >$(LOG) 2>&1 </dev/null & \\
\t\techo $$! >$(PID); echo "started native run (pid $$(cat $(PID))) — follow: make agent-logs WF=$(WF) ; stop: make agent-stop WF=$(WF)"

agent-build: ## Rebuild the worker image, then run the workflow
\t@mkdir -p $(RUNS_DIR)
\t@bash -o pipefail -c '$(ENVV) $(COMPOSE) up --build --abort-on-container-exit --exit-code-from $(WF) $(WF) 2>&1 | tee "$(LOG)"'

agent-hello: ## Smoke-test the worker + auth with the hello-world workflow
\tWORKFLOW_DIR="$(AGENTS_DIR)/workflows/hello-world" PROJECT="$(PROJECT)" AGENT_UID="$(AGENT_UID)" AGENT_GID="$(AGENT_GID)" docker compose -p $(PROJECT) -f $(LOCAL_WORKER)/compose.yaml up --abort-on-container-exit

agent-logs: ## Follow the current run's log (.agents/runs/$(WF).log)
\t@mkdir -p $(RUNS_DIR); touch $(LOG); tail -n +1 -F $(LOG)

agent-container-logs: ## Follow the Docker worker container's logs
\tdocker logs -f $(PROJECT)-$(WF)-1

agent-stop: ## Stop a detached native run started with agent-native-bg
\t@if [ -f $(PID) ] && kill -0 $$(cat $(PID)) 2>/dev/null; then \\
\t\tP=$$(cat $(PID)); pkill -TERM -P $$P 2>/dev/null || true; kill -TERM $$P 2>/dev/null || true; \\
\t\techo "stopped native run (pid $$P)"; rm -f $(PID); \\
\telse echo "no running native run (pidfile absent or stale)"; rm -f $(PID) 2>/dev/null || true; fi

agent-down: ## Stop/remove worker containers (keeps volumes & agent work)
\t$(ENVV) $(COMPOSE) down

agent-reseed-auth: agent-down ## Re-seed subscription creds from the host (clears sessions volume)
\t-docker volume rm $(PROJECT)_claude-state

agent-clean: ## Remove ALL worker volumes — clone, sessions, AND run artifacts
\t$(ENVV) $(COMPOSE) down -v

agent-artifacts: ## Copy run artifacts out of the runs volume into ./.agents/runs
\t@mkdir -p $(CURDIR)/.agents/runs
\tdocker run --rm \\
\t\t-v $(PROJECT)_runs:/runs:ro \\
\t\t-v $(CURDIR)/.agents/runs:/out \\
\t\talpine sh -c 'cp -a /runs/. /out/ 2>/dev/null || true; ls -la /out'
"""

    return f"""{header}{core}{wf_vars}
.DEFAULT_GOAL := help

.PHONY: help{phony_wf} agent-install agent-check

help: ## Show available targets
\t@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | sort | \\
\t\tawk 'BEGIN{{FS=":.*?## "}}{{printf "  \\033[36m%-22s\\033[0m %s\\n", $$1, $$2}}'
{wf_targets}
agent-install: ## Regenerate the agent adapters/skills/workflows from the prompt library
\t$(FARRIER) --repo "$(CURDIR)" $(FARRIER_LIB_ARG)

agent-check: ## Verify generated agent adapters are up to date (no writes)
\t@$(FARRIER) --repo "$(CURDIR)" --check $(FARRIER_LIB_ARG) \\
\t\t&& echo "✓ agent files are up to date" \\
\t\t|| {{ echo "↑ files above would be rewritten by 'make agent-install'"; exit 1; }}
"""


def render_local_compose(workflows: list[str], meta: dict[str, Any]) -> str:
    """Generic local-run compose override (.agents/local.compose.yaml).

    One named service per installed workflow (e.g. `coder:`, `author:`), sharing
    a single build definition — and image tag, so compose builds it only once —
    via the `x-agent-build`/`x-agent-image` anchors below. An explicit
    ``workflow.repoUrl`` clones the remote with the configured token; otherwise
    each service clones a read-only bind mount of the host working tree.
    """
    src_target = f"/mnt/{kebab(meta['repo_name'])}-src"
    remote_checkout = bool(meta.get("remote_checkout"))
    agents = meta.get("agents") or {}
    claude_enabled = bool(agents.get("claude"))
    if remote_checkout:
        repo_environment = (
            f"      # Explicit agents.yml workflow.repoUrl: clone the remote repository.\n"
            f"      REPO_URL: ${{REPO_URL:-{meta['repo_url']}}}\n"
            "      AGENT_CONFIG_FILE: /repo-config/agents.yml\n"
        )
        repo_source_mount = (
            "      - type: bind\n"
            f"        source: ${{REPO_CONFIG:-{meta.get('repo_config_default', './agents.yml')}}}\n"
            "        target: /repo-config/agents.yml\n"
            "        read_only: true\n"
        )
        checkout_description = (
            "# Each service clones the remote configured by agents.yml workflow.repoUrl.\n"
            "# Workflow scripts own authentication using opaque envPassthrough values;\n"
            "# Farrier does not interpret credential configuration.\n"
            "# Each clone lives in that workflow's own workspace volume.\n"
        )
    else:
        repo_environment = (
            "      # No explicit workflow.repoUrl: clone the read-only host checkout.\n"
            f"      REPO_URL: {src_target}\n"
        )
        repo_source_mount = (
            "      - type: bind\n"
            f"        source: ${{REPO_SRC:-{meta.get('repo_src_default', '.')}}}\n"
            f"        target: {src_target}\n"
            "        read_only: true\n"
        )
        checkout_description = (
            "# Each service clones this repo from a READ-ONLY bind mount of your working\n"
            "# tree instead of GitHub, so the host working tree is never mutated.\n"
            "# Each clone lives in that workflow's own workspace volume.\n"
        )
    # Forward declared host env vars into the container, interpolated from the
    # local env at `docker compose up` time (e.g. a GitHub token for PRs).
    passthrough = meta.get("env_passthrough") or []
    passthrough_block = ""
    if passthrough:
        passthrough_block = (
            "      # Host env vars forwarded per agents.yml workflow.envPassthrough\n"
            "      # (interpolated from the local env at `docker compose up`; empty if unset).\n"
            + "".join(f"      {name}: ${{{name}:-}}\n" for name in passthrough)
        )

    claude_environment_block = ""
    claude_credentials_mount = ""
    if claude_enabled:
        claude_environment_block = (
            "      CLAUDE_CODE_OAUTH_TOKEN: ${CLAUDE_CODE_OAUTH_TOKEN:-}\n"
        )
        claude_credentials_mount = """      # Claude subscription credentials — seeded into /claude-state by the workhorse entrypoint.
      - type: bind
        source: ${HOME}/.claude/.credentials.json
        target: /mnt/claude-credentials.json
        read_only: true
"""

    # Docker-outside-of-Docker: lets the coder container bring up this product's
    # own dev stack (docker compose) for QA against the story's `## Verification
    # setup` stack (see coder/prompts/qa-story.md's qa_stack handling), as a
    # sibling container on the host daemon. Only coder needs this — author never
    # runs a dev stack.
    docker_sock_block = (
        "      - type: bind\n"
        "        source: /var/run/docker.sock\n"
        "        target: /var/run/docker.sock\n"
    )

    services = "".join(
        f"""  {wf}:
    image: *agent-image
    build: *agent-build
    # Run as the HOST user's uid:gid so the agent can write into bind-mounted
    # host paths it does not own (e.g. git worktree metadata written back into
    # the source repo). agents.mk exports these from `id -u`/`id -g`; the 65534
    # fallback is nobody:nogroup — the previous fixed-user behavior.
    user: "${{AGENT_UID:-65534}}:${{AGENT_GID:-65534}}"
    extra_hosts:
      # Lets the container's groom-sidecar — installed as an editable uv tool
      # when the GROOM_SRC bind below is set — reach a loopback-bound `groom`
      # dashboard on the host, regardless of which docker network this compose
      # project uses.
      #
      # NOTE (native Linux Docker Engine): host-gateway resolves to the
      # docker bridge's own gateway IP (e.g. 172.17.0.1), NOT the host's real
      # loopback interface — that equivalence only holds on Docker Desktop's
      # (Mac/Windows) VM-proxied host.docker.internal. `groom serve` therefore
      # defaults to binding 0.0.0.0 (reachable over the bridge); if you override
      # it with --host, use the bridge IP, not 127.0.0.1.
      - "host.docker.internal:host-gateway"
    environment:
{claude_environment_block}      # Workflow runtime.
      WORKFLOW_PATH: /workflow/workflow.yaml
      AGENT_RUNS_DIR: /runs
      DISABLE_AUTOUPDATER: "1"
{repo_environment}
      REPO_BRANCH: ${{REPO_BRANCH:-{meta["branch"]}}}
      # Repository name → /workspace/$REPO_NAME inside the container.
      REPO_NAME: ${{REPO_NAME:-{meta["repo_name"]}}}
      # Scripts (e.g. author's load-config.py) resolve the consuming repo via
      # this var rather than CWD — mirrors the native `agent-run` target's
      # AGENT_REPO_DIR="$(CURDIR)", but here CWD is /app (the image's WORKDIR),
      # not the checkout_workspace() clone under /workspace.
      AGENT_REPO_DIR: /workspace/${{REPO_NAME:-{meta["repo_name"]}}}
{passthrough_block}    volumes:
{claude_credentials_mount}      - type: bind
        source: ${{AGENTS_DIR:-{meta["agents_dir"]}}}/workflows/{wf}
        target: /workflow
{repo_source_mount}
      # Optional: host directory containing a .code-workspace file, for
      # multi-repo runs (or non-git sibling folders that can't be cloned — see
      # workhorse/workhorse/scriptutil.py's checkout_workspace()). Uncomment and
      # set WORKSPACE_DIR_HOST; point the workspace-file env var (e.g.
      # CODER_WORKSPACE, forwarded via envPassthrough above) at this mount's
      # target below, not the host path.
      # - type: bind
      #   source: ${{WORKSPACE_DIR_HOST:?Set WORKSPACE_DIR_HOST}}
      #   target: /mnt/workspace-host
      # Optional: the groom-sidecar (dashboard monitoring + live reload). groom is
      # not baked into the image; uncomment this and set GROOM_SRC to your host
      # `groom/` checkout (e.g. .../stablemate/groom) to have the entrypoint
      # install it as an editable uv tool from the bind. Edits then reach the
      # sidecar via a `reload` over the socket (or `docker restart`) with no image
      # rebuild — the `pipx install --editable` model. Omit it and the workflow
      # runs without a sidecar.
      # - type: bind
      #   source: ${{GROOM_SRC:?Set GROOM_SRC to your host groom/ checkout}}
      #   target: /mnt/groom-src
      #   read_only: true
      - type: volume
        source: workspace-{wf}
        target: /workspace
      - type: volume
        source: claude-state
        target: /claude-state
      - type: volume
        source: runs
        target: /runs
{docker_sock_block if wf == "coder" else ""}
"""
        for wf in workflows
    )

    # Each workflow gets its OWN repo checkout volume — author and coder must
    # never share a `/workspace/<repo>` clone. They run independently and on
    # different schedules; a shared volume means whichever one starts second
    # inherits (and can reset-clobber) the other's in-progress working tree.
    # claude-state/runs stay shared: they're keyed by workflow via env
    # (AGENT_RUNS_DIR subpaths, per-session Claude state), not by volume.
    workspace_volumes = "".join(f"  workspace-{wf}:\n" for wf in workflows)

    return f"""# Local-run override for the agent launcher (generated).
#
# Generated by farrier. Layered on top of the shared workhorse compose file:
#   docker compose -f <local-worker>/compose.yaml -f .agents/local.compose.yaml up <WF>
# (the `make agent-run WF=<name>` target does this for you).
#
# One named service per installed workflow ({", ".join(workflows)}), all sharing
# a single build definition and image tag via the anchors below — the image is
# built once no matter how many workflow services run (`docker compose up
# {" ".join(workflows)}` runs them together from this one file).
#
{checkout_description}# Workflow workspace volumes are never shared.
# checkout_workspace() only fast-forwards a clean checkout to the configured
# committed state on $REPO_BRANCH; if the container's copy has uncommitted
# changes or commits not yet on origin/$REPO_BRANCH (e.g. a run that blocked
# mid-way), it leaves the checkout alone so that work survives a restart.
x-agent-image: &agent-image ${{PROJECT:-local-worker}}-agent
x-agent-build: &agent-build
  # Build context is the uv workspace ROOT, not the workhorse dir — the
  # Dockerfile needs the workspace's pyproject.toml/uv.lock (workhorse is a
  # workspace member and has no lock file of its own).
  context: ${{STABLEMATE_DIR:?Set STABLEMATE_DIR (see agents.mk)}}
  dockerfile: workhorse/Dockerfile

services:
{services}
volumes:
{workspace_volumes}"""
