"""Generation of the ``.agents/`` launcher scaffolding.

The generated make launcher (agents.mk), plus the path constants naming what the
installer writes there.

Farrier installs **skills and prompts**, not workflows. A workflow is a Python
package found through the ``workhorse.workflows`` entry-point group, so it is
installed with pip/uv and run with ``workhorse run <name>`` — there is nothing for
this module to render per workflow, and the launcher's targets are the two that
regenerate and verify the adapters.
"""
from __future__ import annotations


# Launcher scaffolding generated for every install. These are always-owned
# generated files (registered for --check and cleanup). The thin root Makefile is
# special-cased: it is only written when no root Makefile already exists, and is
# never removed by cleanup (a user may hand-author it).
LAUNCHER_AGENTS_MK = ".agents/agents.mk"
LAUNCHER_CONTEXT_MANIFEST = ".agents/agents-context.json"
# Per-assistant context manifests (one per enabled agent) so a Codex/Copilot run
# resolves instruction_ref to its own adapters. Selected by AGENT_CLI at run time;
# the generic LAUNCHER_CONTEXT_MANIFEST above stays the primary assistant's copy.
LAUNCHER_CONTEXT_MANIFEST_FMT = ".agents/agents-context.{}.json"
LAUNCHER_ROOT_MAKEFILE = "Makefile"
# The compose override farrier generated per installed workflow while workflows
# were a farrier concern. Nothing writes it any more; the constant survives so
# `remove_targets` still deletes a leftover from an older install.
LAUNCHER_COMPOSE = ".agents/local.compose.yaml"


def render_agents_mk() -> str:
    """The make launcher (.agents/agents.mk), generated for every repo.

    Two targets — `agent-install` and `agent-check` — regenerating and verifying
    the adapters farrier renders. A root Makefile can `include` it unconditionally.

    It carries no workflow-run targets: workflows are Python packages resolved
    through workhorse's `workhorse.workflows` entry-point group, not files this
    installer places, so running one is `workhorse run <name>` and needs nothing
    generated per repo.
    """
    header = """# Agent launcher — farrier adapter regeneration (generated).
#
# Generated by farrier (the prompt-library installer). Do not edit by hand;
# re-run `make agent-install` to regenerate. Include it from a root Makefile:
#
#   include .agents/agents.mk
#
# Usage:
#   make agent-install             # regenerate the agent adapters from the library
#   make agent-check               # verify adapters are up to date (no writes)
#
# To run a workflow, install its package and call workhorse directly:
#
#   uv tool install workhorse-workflows
#   workhorse run <name> --dry-run     # static preflight, drives nothing
#   workhorse run <name>
"""

    core = """
AGENTS_DIR     ?= $(shell farrier config show library_dir)
# Public stablemate checkout (holds the farrier installer source). Needed only
# for SRC=1 local-source runs.
STABLEMATE_DIR ?= $(shell farrier config show stablemate_dir)

# farrier regenerates these adapters from the prompt library. Default uses the
# installed farrier binary. SRC=1 runs the local source under $(STABLEMATE_DIR)/farrier.
# The library CONTENT is located via `farrier config set-library`; when a
# vigilant-octo checkout exists at $(AGENTS_DIR) we pass --library explicitly.
ifeq ($(SRC),1)
FARRIER ?= uv run --project $(STABLEMATE_DIR)/farrier farrier
endif
FARRIER ?= farrier
FARRIER_LIB_ARG := $(if $(wildcard $(AGENTS_DIR)/library),--library "$(AGENTS_DIR)",)
"""

    return f"""{header}{core}
.DEFAULT_GOAL := help

.PHONY: help agent-install agent-check

help: ## Show available targets
\t@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | sort | \\
\t\tawk 'BEGIN{{FS=":.*?## "}}{{printf "  \\033[36m%-22s\\033[0m %s\\n", $$1, $$2}}'

agent-install: ## Regenerate the agent adapters/skills from the prompt library
\t$(FARRIER) --repo "$(CURDIR)" $(FARRIER_LIB_ARG)

agent-check: ## Verify generated agent adapters are up to date (no writes)
\t@$(FARRIER) --repo "$(CURDIR)" --check $(FARRIER_LIB_ARG) \\
\t\t&& echo "✓ agent files are up to date" \\
\t\t|| {{ echo "↑ files above would be rewritten by 'make agent-install'"; exit 1; }}
"""
