"""Generation of the ``.agents/`` launcher scaffolding.

The generated make launcher (agents.mk), plus the path constants naming what the
installer writes there.

Farrier installs **skills and prompts**, not workflows — a workflow is a Python
distribution that ships its own console script. But *launching* one in a container
is per-repo generated state again: N concurrent runs of the same workflow need a
distinct run id, container name and volume set each, and none of that is
expressible as a fixed command a reader could be told to type. So the launcher
carries one run target per **installed** workflow.

Which workflows those are is resolved by `farrier workflows --names` **at make
time**, not baked in here at render time. This file is tracked in the repo, and the
installed set is a property of the machine: baking it in would make a tracked file
differ per developer, churn on every `pipx install`, and — for a workflow installed
from a local path — carry somebody's home directory into the repo. Make generates
the per-workflow targets from that list with `$(eval)`, so the targets are real (and
a typo still gets make's own "No rule to make target") while the file stays the same
everywhere. See the internal container-concurrent-runs plan §8.2 and its item-4 note.
"""
from __future__ import annotations


# Launcher scaffolding generated for every install. These are always-owned
# generated files (registered for --check and cleanup). The thin root Makefile is
# special-cased: it is only written when no root Makefile already exists, and is
# never removed by cleanup (a user may hand-author it).
LAUNCHER_AGENTS_MK = ".agents/agents.mk"
LAUNCHER_CONTEXT_MANIFEST = ".agents/agents-context.json"
# Per-assistant context manifests (one per enabled agent) so a Codex/Copilot run
# resolves instruction_ref to its own adapters. Selected by AGENT_CLI at run time;
# the generic LAUNCHER_CONTEXT_MANIFEST above stays the primary assistant's copy.
LAUNCHER_CONTEXT_MANIFEST_FMT = ".agents/agents-context.{}.json"
LAUNCHER_ROOT_MAKEFILE = "Makefile"
# The compose override farrier generated per installed workflow while workflows
# were a farrier concern. Nothing writes it any more; the constant survives so
# `remove_targets` still deletes a leftover from an older install.
LAUNCHER_COMPOSE = ".agents/local.compose.yaml"


_HEADER = """# Agent launcher — farrier adapter regeneration + containerized runs (generated).
#
# Generated by farrier (the prompt-library installer). Do not edit by hand;
# re-run `make agent-install` to regenerate. Include it from a root Makefile:
#
#   include .agents/agents.mk
#
# Usage:
#   make agent-install             # regenerate the agent adapters from the library
#   make agent-check               # verify adapters are up to date (no writes)
#   make farrier-run-hook          # what the repo's pre-commit hook invokes
#   make agent-workflows           # what this machine can run, and where it came from
#   make agent-run-<workflow>      # run one, in its own container
#
# The run targets exist for whatever `farrier workflows` finds installed HERE. That
# list is resolved when you type `make`, not when this file was written: it is a
# property of your machine, and this file is tracked in the repo.
"""

_CORE = """
AGENTS_DIR     ?= $(shell farrier config show library_dir)
# Public stablemate checkout (holds the farrier installer source). Needed only
# for SRC=1 local-source runs.
STABLEMATE_DIR ?= $(shell farrier config show stablemate_dir)

# farrier regenerates these adapters from the prompt library. Default uses the
# installed farrier binary. SRC=1 runs the local source under $(STABLEMATE_DIR)/farrier.
# The library CONTENT is located via `farrier config set-library`; when a
# library checkout exists at $(AGENTS_DIR) we pass --library explicitly.
ifeq ($(SRC),1)
FARRIER ?= uv run --project $(STABLEMATE_DIR)/farrier farrier
endif
FARRIER ?= farrier
FARRIER_LIB_ARG := $(if $(wildcard $(AGENTS_DIR)/library),--library "$(AGENTS_DIR)",)
"""

# The containerized-run plumbing, identical in every repo on every machine.
#
# Everything here is per-RUN, not per-repo. The compose PROJECT name carries the
# isolation: docker compose namespaces its named volumes by project, so
# `-p coder-<uuid>` gives that run its own workspace/claude-state/runs volumes
# without compose.yaml having to declare anything per-run. That matters most for
# claude-state, which is HOME — two runs sharing it would rotate one
# .credentials.json and last-writer-win each other's .gitconfig.
_RUN_PLUMBING = """
# ── Containerized runs (one container per run) ────────────────────────────────
#
# Each `make agent-run-<workflow>` launch is independent: its own container, its
# own volume set, its own run id. Several may be in flight at once.
#
#   make agent-run-<workflow>              # start a run, streaming its logs
#   make agent-run-<workflow> DETACH=1     # start it in the background
#   make agent-run-<workflow> PROFILE=x    # …on a named set of models
#   make agent-runs                        # list live runs
#   make agent-logs RUN=<workflow>-<id>    # follow one
#   make agent-stop RUN=<workflow>-<id>    # SIGTERM it (resumable: docker restart)
#   make agent-clean RUN=<workflow>-<id>   # remove it AND its volumes (destructive)
#
# The container runs as nobody's uid with YOUR group, so what a run writes into a
# bind-mounted host path stays writable from the host.
AGENT_UID  ?= 65534
AGENT_GID  ?= $(shell id -g)

# The container harness lives in the stablemate checkout, not in a published
# package — compose.yaml/Dockerfile are build inputs, not distribution files.
AGENT_COMPOSE ?= $(STABLEMATE_DIR)/workhorse/compose.yaml

# The repo a run works on, and where each run's own `git worktree` of it is cut.
#
# The worktree root lives INSIDE the repo deliberately: the repo is bind-mounted at
# its own host path (git records a worktree's registration on both sides by absolute
# path, so the container and the host must agree), and putting the worktrees under it
# means that one bind covers the source and every run's tree at matching paths.
AGENT_REPO         ?= $(CURDIR)
AGENT_WORKTREE_ROOT ?= $(AGENT_REPO)/.agents/worktrees
# Recursively expanded (`?=`), so this git call only runs for a launch — not for
# every `make` in the including repo.
AGENT_BASE_BRANCH  ?= $(shell git -C "$(AGENT_REPO)" symbolic-ref --quiet --short HEAD 2>/dev/null || echo main)

DETACH ?=
AGENT_UP_FLAGS = $(if $(DETACH),--detach,--abort-on-container-exit)

# Which named model set this run buys, and which config file the name lives in.
#
#   make agent-run-<workflow> PROFILE=cheap
#   make agent-run-<workflow> PROFILE=cheap CONFIG=./ci-config.toml
#
# PROFILE names a `[profiles.<name>]` table (`farrier config show --profile cheap`
# prints one). CONFIG defaults to the machine's own config, so a profile is selectable
# without naming a file. Neither set is the behavior every run had before profiles
# existed: models resolve from the config's top-level tables.
PROFILE ?=
CONFIG  ?=

# One launch. $(1) is the workflow name.
#
# The run id is a UUID minted HERE rather than derived inside the container: every
# container starts in the same cwd with the same params, so workhorse's
# params-digest fallback hands every one of them an identical run id, and a second
# run would resume — or delete — the first. An explicit --run-id always wins over
# the digest, so this is a launcher fix: workhorse's digest stays correct for
# interactive local runs, where re-running the same command *should* resume.
#
# The id is interpolated into the container's config at create time, which buys the
# right restart semantics for free: `docker restart` re-enters with the same id and
# resumes from the checkpoint, while a fresh `make` mints a new id and starts clean.
define agent_launch
	set -eu; \\
	run_id="$$(cat /proc/sys/kernel/random/uuid)"; \\
	project="$(1)-$$run_id"; \\
	repo_name="$$(basename "$(AGENT_REPO)")"; \\
	worktree_root="$(AGENT_WORKTREE_ROOT)/$$run_id"; \\
	run_auth="$$worktree_root/.credentials.json"; \\
	run_config="$$worktree_root/stablemate-config.toml"; \\
	mkdir -p "$$worktree_root"; \\
	$(agent_stage_credentials) \\
	$(agent_stage_config) \\
	$(agent_share_with_container) \\
	echo "[agent] workflow  : $(1)"; \\
	test -z "$(PROFILE)" || echo "[agent] profile   : $(PROFILE) (from $$run_config)"; \\
	echo "[agent] run id    : $$run_id"; \\
	echo "[agent] container : $$project"; \\
	echo "[agent] worktree  : $$worktree_root/$$repo_name"; \\
	echo "[agent] follow    : make agent-logs RUN=$$project"; \\
	WORKFLOW="$(1)" \\
	AGENT_RUN_ID="$$run_id" \\
	AGENT_UID="$(AGENT_UID)" AGENT_GID="$(AGENT_GID)" \\
	AGENT_CREDENTIALS_FILE="$$run_auth" \\
	AGENT_CONFIG_FILE="$$run_config" \\
	AGENT_CONFIG="$$run_config" \\
	AGENT_PROFILE="$(PROFILE)" \\
	AGENT_REPO_HOST_DIR="$(AGENT_REPO)" \\
	AGENT_SOURCE_MODE=worktree \\
	AGENT_WORKTREE_ROOT="$$worktree_root" \\
	AGENT_REPO_DIR="$$worktree_root/$$repo_name" \\
	REPO_URL="$(AGENT_REPO)" \\
	REPO_NAME="$$repo_name" \\
	REPO_BRANCH="$(AGENT_BASE_BRANCH)" \\
	docker compose -p "$$project" -f "$(AGENT_COMPOSE)" up $(AGENT_UP_FLAGS)
endef

# Your Claude subscription credentials, where a non-you container can read them.
#
# The container runs as nobody's uid with your group, and ~/.claude/.credentials.json
# is mode 600 — owner-only, so group access buys nothing and the run dies at "Not
# logged in". Three ways out were weighed (see the plan's item 8): chmod your real
# credentials 640 (the CLI rewrites that file on token rotation and would silently
# restore 600 later), run the container as you (gives it your uid everywhere it is
# mounted), or stage a copy. Staging wins because it changes nothing you own and
# cannot rot.
#
# The copy is per-run, mode 640, group-owned by you, and lives beside the run's
# worktree rather than inside it — `agent-clean` takes it with the rest of the run.
# `.agents/` is gitignored, so it is never committed. Skipped silently when you have
# no credentials file: CLAUDE_CODE_OAUTH_TOKEN is the other supported path, and
# compose falls back to binding your real file for a container that runs as you.
define agent_stage_credentials
	if [ -r "$$HOME/.claude/.credentials.json" ]; then \\
		install -m 640 "$$HOME/.claude/.credentials.json" "$$run_auth"; \\
	fi;
endef

# The config this run resolves its models from — a COPY, per run.
#
# The config is re-read every turn, so binding the operator's own file live would
# mean an edit to it silently moving the models of every container already going.
# That global mutation is exactly what naming a profile is meant to end, so the file
# is snapshotted at launch: what a run starts on is what it finishes on, and a
# `docker restart` resumes on it too. It is staged beside the worktree, under the
# gitignored `.agents/`, so `agent-clean` takes it with the rest of the run.
#
# An unreadable CONFIG is fatal rather than ignored: falling back to the machine's
# config would run a CI or benchmark launch on models nobody chose, and report
# success. Same for a PROFILE with no config behind it — the profile would resolve
# to nothing and the run would quietly take the harness defaults.
define agent_stage_config
	config_src="$(CONFIG)"; \\
	if [ -n "$$config_src" ] && [ ! -r "$$config_src" ]; then \\
		echo "[agent] CONFIG=$$config_src is not readable" >&2; exit 2; \\
	fi; \\
	[ -n "$$config_src" ] || config_src="$${STABLEMATE_CONFIG:-$$HOME/.config/stablemate/config.toml}"; \\
	if [ -r "$$config_src" ]; then \\
		install -m 644 "$$config_src" "$$run_config"; \\
	else \\
		test -z "$(PROFILE)" || { \\
			echo "[agent] PROFILE=$(PROFILE) but no config at $$config_src" >&2; exit 2; }; \\
		run_config=""; \\
	fi;
endef

# Make what the container writes usable from the host afterwards.
#
# The container runs as nobody's uid with YOUR group (see AGENT_UID/AGENT_GID), so
# group access is the only thing bridging the two — and by default git works against
# that: it writes loose objects mode 0444, no group write bit anywhere.
# `core.sharedRepository=group` is what relaxes it, and it has to be set on the
# SOURCE repo, because that is where a worktree's objects land.
#
# Set here rather than inside the container on purpose: this is the operator's own
# repo, and it should be configured by something running as the operator. It is
# persistent and it does change how their own git writes — so it is announced, and
# only set when absent. Undo with `git config --unset core.sharedRepository`.
#
# setgid on the worktree root makes every directory created beneath it inherit the
# group, which is what keeps the umask's 775 meaningful for paths the container mints.
define agent_share_with_container
	if [ -z "$$(git -C "$(AGENT_REPO)" config --local core.sharedRepository || true)" ]; then \\
		git -C "$(AGENT_REPO)" config --local core.sharedRepository group; \\
		echo "[agent] set core.sharedRepository=group on $(AGENT_REPO) (so the"; \\
		echo "[agent]   container's commits stay writable from the host)"; \\
	fi; \\
	chmod g+s "$$worktree_root";
endef

# RUN names a launched run by its compose project (`<workflow>-<run-id>`), which is
# what agent-runs prints and what the launch echoed.
define agent_require_run
	@test -n "$(RUN)" || { \\
		echo "set RUN=<workflow>-<run-id> (see: make agent-runs)" >&2; exit 2; }
endef

# One `agent-run-<workflow>` target per workflow installed on THIS machine.
#
# Discovered when make parses this file, not when farrier wrote it — the installed
# set belongs to the machine, and this file is tracked in the repo. Baking the list
# in would make it differ per developer, churn on every `pipx install`, and (for a
# workflow installed from a local path) carry somebody's home directory into a
# commit. `$(eval)` still produces REAL targets, so `make agent-run-typo` gets
# make's own "No rule to make target" rather than a run of nothing.
#
# The discovery only runs when a run target is actually being asked for, so `make
# help` — or any unrelated target in the including Makefile — pays nothing for it.
define agent_run_target
agent-run-$(1): ## Run the `$(1)` workflow in its own container
\t@$$(call agent_launch,$(1))
endef

ifneq ($(filter agent-run-%,$(MAKECMDGOALS)),)
AGENT_WORKFLOWS := $(shell $(FARRIER) workflows --names)
$(foreach wf,$(AGENT_WORKFLOWS),$(eval $(call agent_run_target,$(wf))))
.PHONY: $(addprefix agent-run-,$(AGENT_WORKFLOWS))
endif
"""

_REGEN_TARGETS = """
.DEFAULT_GOAL := help

{phony}

help: ## Show available targets
\t@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) | sort | \\
\t\tawk 'BEGIN{{FS=":.*?## "}}{{printf "  \\033[36m%-22s\\033[0m %s\\n", $$1, $$2}}'

agent-install: ## Regenerate the agent adapters/skills from the prompt library
\t$(FARRIER) --repo "$(CURDIR)" $(FARRIER_LIB_ARG)

agent-check: ## Verify generated agent adapters are up to date (no writes)
\t@$(FARRIER) --repo "$(CURDIR)" --check $(FARRIER_LIB_ARG) \\
\t\t&& echo "✓ agent files are up to date" \\
\t\t|| {{ echo "↑ files above would be rewritten by 'make agent-install'"; exit 1; }}
"""

_RUN_TARGETS = """
agent-workflows: ## Show which workflows this machine can run, and where they came from
\t@$(FARRIER) workflows

agent-runs: ## List live containerized runs
\t@docker ps --filter label=com.docker.compose.service=agent \\
\t\t--format 'table {{.Label "com.docker.compose.project"}}\\t{{.Status}}\\t{{.Names}}'

agent-logs: ## Follow one run's logs (RUN=<workflow>-<run-id>)
\t$(call agent_require_run)
\t@docker compose -p "$(RUN)" -f "$(AGENT_COMPOSE)" logs -f

agent-stop: ## Stop one run, leaving its volumes so `docker restart` resumes it
\t$(call agent_require_run)
\t@docker compose -p "$(RUN)" -f "$(AGENT_COMPOSE)" stop

agent-clean: ## Remove one run's container AND its per-run volumes (destructive)
\t$(call agent_require_run)
\t@docker compose -p "$(RUN)" -f "$(AGENT_COMPOSE)" down -v
"""


def render_agents_mk() -> str:
    """The make launcher (.agents/agents.mk), generated for every repo.

    Byte-identical everywhere, deliberately. It carries `agent-install` and
    `agent-check` (which regenerate and verify the adapters farrier renders) plus
    the containerized-run plumbing, and it derives one `agent-run-<workflow>` target
    per **installed** workflow by asking `farrier workflows --names` when make parses
    it. Nothing about which workflows exist is written into this file.

    The installed set is the only source of truth for what is runnable — a selection
    list in `agents.yml` would be a second one, going stale the moment someone
    pipx-installs or uninstalls. But it is a property of the *machine*, and this file
    is tracked in the repo, so the resolution has to happen at make time rather than
    at render time. See the comment above `agent_run_target` in the emitted file.
    """
    phony = (
        ".PHONY: help agent-install agent-check farrier-run-hook "
        "agent-workflows agent-runs agent-logs agent-stop agent-clean"
    )
    return (
        f"{_HEADER}{_CORE}{_RUN_PLUMBING}"
        f"{_REGEN_TARGETS.format(phony=phony)}{_RUN_TARGETS}"
    )
