"""Which files farrier may delete, and which it must refuse to overwrite.

farrier used to prune by *location*: every file under a managed directory was
deleted before each render, on the assumption that anything living there was
farrier's. That assumption is what stopped a repo from keeping one hand-written
skill next to the generated ones — the next install removed it silently, and the
only evidence was somebody's missing file.

Ownership is a property of the *file*, not of where it sits. A generated skill or
prompt says so in its front matter (``metadata.generated_by: farrier``, written by
``renderer.skill_metadata_block``); a generated file that cannot carry front matter —
an aggregated instruction file, a Makefile include, a hook runner — says the same
thing in a comment near the top, in the shape ``renderer.local_instruction_banner``
already emits and ``frontmatter.banner_sources`` already parses.

Two consequences, and they are the point of the module:

* **Deletion is a scan, not an ``rmtree``.** Only tagged files go, so an untagged
  neighbour survives every install.
* **An untagged file at a path farrier is about to write is a conflict**, and a
  conflict aborts the whole install rather than being overwritten. The operator
  renames or deletes their file; farrier does not decide that for them.

Not everything can be tagged. A JSON manifest has no comment syntax, and inventing
provenance inside its object would change the document a reader parses — those paths
stay owned by convention and are listed as such by the caller.
"""
from __future__ import annotations

from pathlib import Path

from farrier.frontmatter import frontmatter_metadata

#: The ``metadata.generated_by`` value stamping a generated skill, prompt or command.
TAG = "farrier"

#: What a generated file with nowhere to put front matter says instead. Matched
#: case-insensitively, so both "Generated by farrier" (the Makefile/hook comment
#: leader) and the banner's "generated by farrier from the agent library" hit.
COMMENT_MARKER = "generated by farrier"

#: How far into a file the comment marker is looked for. A banner is the first thing
#: in the file; the allowance is for a shebang, a leading blank line, or a couple of
#: lines of preamble above the comment — not for the phrase turning up in prose.
COMMENT_SCAN_LINES = 12


def is_tagged(text: str) -> bool:
    """True when *text* carries farrier's generated-by mark, in either spelling."""
    if str(frontmatter_metadata(text).get("generated_by", "")) == TAG:
        return True
    head = text.split("\n")[:COMMENT_SCAN_LINES]
    return COMMENT_MARKER in "\n".join(head).lower()


def is_generated(path: Path) -> bool:
    """True when *path* is a file farrier generated, judged by its own contents.

    A file that cannot be read as text is never farrier's: everything farrier writes
    is UTF-8, so an unreadable or binary file at a managed path belongs to somebody
    else and must survive.
    """
    if not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    return is_tagged(text)


def is_owned(path: Path, root: Path) -> bool:
    """True when farrier owns *path* — directly, or through the skill bundling it.

    A generated ``SKILL.md`` claims its whole directory. Its bundled ``scripts/`` run
    byte-for-byte as written and cannot take a comment leader that is right in every
    language, so they carry no mark of their own; a skill and its assets install as one
    unit and are owned as one unit.

    *root* bounds the walk to directories strictly below it, so a ``SKILL.md`` sitting
    somewhere above a managed directory cannot claim what is inside it.
    """
    if is_generated(path):
        return True
    parent = path.parent
    while root in parent.parents:
        if is_generated(parent / "SKILL.md"):
            return True
        parent = parent.parent
    return False


def owned_files(directory: Path) -> list[Path]:
    """Every file under *directory* that farrier generated, in path order."""
    if not directory.is_dir():
        return []
    return [
        path
        for path in sorted(directory.rglob("*"))
        if path.is_file() and is_owned(path, directory)
    ]


def sweep(directory: Path) -> None:
    """Delete farrier's files under *directory*, leaving everything else in place.

    Directories emptied by the sweep go too — a skill that is no longer selected must
    not leave its folder behind for ``--check`` to report as a stray. A directory still
    holding somebody else's file stays, along with every parent above it.
    """
    if not directory.is_dir():
        return
    for path in owned_files(directory):
        path.unlink()
    for path in sorted(
        (item for item in directory.rglob("*") if item.is_dir()), reverse=True
    ):
        if not any(path.iterdir()):
            path.rmdir()
