"""Which files farrier may delete, and which it must refuse to overwrite."""
from __future__ import annotations

from pathlib import Path

from farrier.frontmatter import frontmatter_metadata

TAG = "farrier"

COMMENT_MARKER = "generated by farrier"

COMMENT_SCAN_LINES = 12


def is_tagged(text: str) -> bool:
    """True when *text* carries farrier's generated-by mark, in either spelling."""
    if str(frontmatter_metadata(text).get("generated_by", "")) == TAG:
        return True
    head = text.split("\n")[:COMMENT_SCAN_LINES]
    return COMMENT_MARKER in "\n".join(head).lower()


def is_generated(path: Path) -> bool:
    """True when *path* is a file farrier generated, judged by its own contents."""
    if not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return False
    return is_tagged(text)


def is_owned(path: Path, root: Path) -> bool:
    """True when farrier owns *path* — directly, or through the skill bundling it."""
    if is_generated(path):
        return True
    parent = path.parent
    while root in parent.parents:
        if is_generated(parent / "SKILL.md"):
            return True
        parent = parent.parent
    return False


def owned_files(directory: Path) -> list[Path]:
    """Every file under *directory* that farrier generated, in path order."""
    if not directory.is_dir():
        return []
    return [
        path
        for path in sorted(directory.rglob("*"))
        if path.is_file() and is_owned(path, directory)
    ]


def sweep(directory: Path) -> None:
    """Delete farrier's files under *directory*, leaving everything else in place."""
    if not directory.is_dir():
        return
    for path in owned_files(directory):
        path.unlink()
    for path in sorted(
        (item for item in directory.rglob("*") if item.is_dir()), reverse=True
    ):
        if not any(path.iterdir()):
            path.rmdir()
