"""The ``Renderer`` — stateful rendering of library sources into agent adapters.

Holds the selected skills/prompts and per-repo context, and renders each into the
Codex/Claude/Copilot file layouts, stamping provenance as it goes.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from jinja2 import Environment, StrictUndefined

from farrier.frontmatter import first_heading, split_front_matter
from farrier.launcher import (
    DEFAULT_AGENTS_DIR,
    LAUNCHER_AGENTS_MK,
    LAUNCHER_COMPOSE,
    LAUNCHER_CONTEXT_MANIFEST,
    LAUNCHER_CONTEXT_MANIFEST_FMT,
    LAUNCHER_ROOT_MAKEFILE,
    render_agents_mk,
    render_local_compose,
)
from farrier.layers import available_names, find_in_layers
from farrier.naming import kebab, relative_reference, yaml_quote
from farrier.selection_errors import unknown_selection_error
from farrier.sources import Source, build_lookup, library_source_path, public_name
from farrier.workflows import extract_workflow_dependencies


# A generated skill/command is a *copy* of a library source. Without a marker, an
# agent editing it "fixes" the copy — losing the change on the next `make
# agent-install`. We stamp the single source of truth into a `metadata` front-matter
# field so the edit lands in the library instead. Skills carry it natively (openskill
# format: openskill.sh/docs/creators/skill-format); Claude commands carry the same
# block — the slash-command parser (and claude-code-acp) ignores keys it does not
# recognise, so `metadata` is inert to the agent. Codex/copilot prompts are left
# untouched; aggregated Claude instruction files get an HTML-comment banner instead
# (see local_instruction_banner).
def skill_metadata_block(source: Source, dest_rel: str) -> str:
    """The `metadata:` block stamping a generated skill/command with its source.

    *dest_rel* is the generated file's repo-root-relative path — it makes the
    `resolve:` field a copy-pasteable command that turns the (machine-independent,
    library-anchored) `source:` back into this machine's absolute editable path via
    ``farrier source`` (which reuses the same library resolution as install). The
    header stays portable: no absolute path is baked in, so it is stable across
    machines and under ``--check``.

    Returns the YAML lines (newline-terminated) to splice into the front matter.
    """
    do_not_edit = (
        "generated — run the `resolve` command below for this machine's editable "
        "source path, edit that, then `make agent-install` to regenerate"
    )
    return (
        "metadata:\n"
        "  generated_by: farrier\n"
        f"  source: {library_source_path(source)}\n"
        f"  resolve: {yaml_quote(f'farrier source {dest_rel}')}\n"
        f"  do_not_edit: {yaml_quote(do_not_edit)}\n"
    )


# Aggregated instruction files (localInstructions → CLAUDE.md) cannot carry YAML
# front matter — Claude injects them into context verbatim, so a `metadata:` block
# would read as instructions. Provenance rides in a block-level HTML comment
# instead: Claude strips those before *context injection*, but anyone (human or
# agent) opening the file to edit it sees the comment raw — exactly the audience
# that must be redirected to the library source. Only the claude target gets it;
# other agents do not strip comments.
def local_instruction_banner(sources: list[Source], dest_rel: str) -> str:
    """The DO-NOT-EDIT comment prepended to generated Claude instruction files.

    *dest_rel* is the generated file's repo-root-relative path — like
    skill_metadata_block's `resolve:` field, it makes the banner's resolve line a
    copy-pasteable ``farrier source`` command that turns the library-anchored
    source paths into this machine's absolute editable paths, keeping the banner
    itself portable and stable under ``--check``.
    """
    source_lines = "\n".join(f"  {library_source_path(s)}" for s in sources)
    return (
        "<!--\n"
        "DO NOT EDIT — generated by farrier from the agent library.\n"
        "Edits here are overwritten by `make agent-install` (or: farrier --repo .).\n"
        "Edit the library source(s) instead, then regenerate:\n"
        f"{source_lines}\n"
        f"Editable paths on this machine: `farrier source {dest_rel}`\n"
        "Skill→path mapping: agents.yml → localInstructions\n"
        "-->\n\n"
    )


class Renderer:
    def __init__(
        self,
        repo: Path,
        prefix: str,
        repo_config: dict[str, Any],
        template_values: dict[str, Any],
        skills: list[Source],
        prompts: list[Source],
    ):
        self.repo = repo
        self.prefix = prefix
        self.repo_context = dict(repo_config)
        self.repo_context.setdefault("name", kebab(repo.name))
        self.repo_context["prefix"] = prefix
        self.repo_context["root"] = repo.as_posix()
        self.template_values = template_values
        self.skills = skills
        self.prompts = prompts
        self.skill_lookup = build_lookup(skills, prefix)
        self.prompt_lookup = build_lookup(prompts, prefix)

    def skill_source(self, name: str) -> Source:
        source = self.optional_skill_source(name)
        if source is None:
            raise SystemExit(f"Unknown selected skill reference: {name}")
        return source

    def optional_skill_source(self, name: str) -> Source | None:
        key = name.replace(".", "-")
        source = self.skill_lookup.get(key)
        if source is None and self.prefix and not key.startswith(f"{self.prefix}-"):
            # A repo-prefixed overlay skill (e.g. acme-developer) stays
            # addressable by its generic name ("developer") so shared workflow
            # prompts can reference the repo's overlay without knowing the repo.
            source = self.skill_lookup.get(f"{self.prefix}-{key}")
        return source

    def prompt_source(self, name: str) -> Source:
        key = name.replace(".", "-")
        if key not in self.prompt_lookup:
            raise SystemExit(f"Unknown selected prompt reference: {name}")
        return self.prompt_lookup[key]

    def optional_prompt_source(self, name: str) -> Source | None:
        return self.prompt_lookup.get(name.replace(".", "-"))

    def skill_output_path(self, name: str, target: str) -> Path:
        source = self.skill_source(name)
        generated = public_name(self.prefix, source)
        if target == "copilot-instruction":
            return (
                self.repo / ".github" / "instructions" / f"{generated}.instructions.md"
            )
        if target == "copilot":
            return self.repo / ".github" / "skills" / generated / "SKILL.md"
        if target == "codex":
            return self.repo / ".agents" / "skills" / generated / "SKILL.md"
        if target == "claude":
            return self.repo / ".claude" / "skills" / generated / "SKILL.md"
        raise SystemExit(f"Unknown skill render target: {target}")

    def prompt_output_path(self, name: str, target: str) -> Path:
        source = self.prompt_source(name)
        generated = public_name(self.prefix, source)
        if target == "copilot":
            return self.repo / ".github" / "prompts" / f"{generated}.prompt.md"
        if target == "codex":
            return self.repo / ".agents" / "prompts" / f"{generated}.prompt.md"
        if target == "claude":
            return self.repo / ".claude" / "commands" / f"{generated}.md"
        raise SystemExit(f"Unknown prompt render target: {target}")

    def skill_dir_path(self, target: str) -> Path:
        if target == "copilot":
            return self.repo / ".github" / "skills"
        if target == "codex":
            return self.repo / ".agents" / "skills"
        if target == "claude":
            return self.repo / ".claude" / "skills"
        raise SystemExit(f"Unknown skill dir target: {target}")

    def render_templates(self, content: str, target: str, from_file: Path) -> str:
        if not any(
            token in content
            for token in [
                "instruction_file(",
                "instruction_ref(",
                "skill_file(",
                "prompt_file(",
                "prompt_ref(",
                "skill_dir(",
                "isUsingInstruction(",
                "repo.",
                "template.",
                "vars.",
            ]
        ):
            return content
        env = Environment(autoescape=False, undefined=StrictUndefined)
        template = env.from_string(content)
        skill_target = "copilot-instruction" if target == "copilot" else target

        def instruction_ref(name: str) -> str:
            if self.optional_skill_source(name):
                return relative_reference(
                    from_file, self.skill_output_path(name, skill_target)
                )
            return f"generated {name} instruction file when installed"

        def prompt_ref(name: str) -> str:
            if self.optional_prompt_source(name):
                return relative_reference(
                    from_file, self.prompt_output_path(name, target)
                )
            return f"generated {name} prompt when installed"

        def skill_file(name: str) -> str:
            if self.optional_skill_source(name):
                return relative_reference(
                    from_file, self.skill_output_path(name, target)
                )
            return f"generated {name} skill when installed"

        def prompt_file_fn(name: str) -> str:
            if self.optional_prompt_source(name):
                return relative_reference(
                    from_file, self.prompt_output_path(name, target)
                )
            return f"generated {name} prompt when installed"

        def is_using_instruction(instruction_name: str) -> bool:
            """Check if this project has a specific instruction selected."""
            return self.optional_skill_source(instruction_name) is not None

        def workhorse_var(name: str) -> str:
            """Emit a runtime variable reference that workhorse will fill at run time.
            Usage in templates: {{ workhorse_var('plan_path') }}
            Output in installed file: {{ plan_path }}"""
            return "{{ " + name + " }}"

        return template.render(
            instruction_file=lambda name: (
                relative_reference(
                    from_file, self.skill_output_path(name, skill_target)
                )
                if self.optional_skill_source(name)
                else f"generated {name} instruction file when installed"
            ),
            instruction_ref=instruction_ref,
            skill_file=skill_file,
            prompt_file=prompt_file_fn,
            prompt_ref=prompt_ref,
            skill_dir=lambda: relative_reference(
                from_file, self.skill_dir_path(target)
            ),
            isUsingInstruction=is_using_instruction,
            workhorse_var=workhorse_var,
            repo=self.repo_context,
            template=self.template_values,
            vars=self.template_values,
            target=target,
        )

    def context_manifest(self, target: str) -> dict[str, Any]:
        """Per-repo manifest consumed by workhorse at run time (see workhorse/templates.py).

        Workflows now run **directly from the library** — they are never copied or
        rendered into a repo. This manifest captures exactly what the install-time
        template helpers used to resolve (``instruction_ref``/``isUsingInstruction``/
        ``template.*``/``skill_dir``), so the library-resident prompts render at run
        time. All paths are **repo-root-relative** because the agent runs with its
        working directory at the repo root (``AGENT_REPO_DIR``).
        """
        def rel(path: Path) -> str:
            return path.relative_to(self.repo).as_posix()

        instructions = {
            key: rel(self.skill_output_path(source.id, target))
            for key, source in self.skill_lookup.items()
        }
        prompts = {
            key: rel(self.prompt_output_path(source.id, target))
            for key, source in self.prompt_lookup.items()
        }
        # The manifest is a committed adapter consumed at run time with the working
        # directory AT the repo root, so pin repo.root to "." — keeping the install
        # machine's absolute path out of version control (avoids cross-machine drift).
        repo_context = {**self.repo_context, "root": "."}
        return {
            "template": self.template_values,
            "repo": repo_context,
            "vars": self.template_values,
            "instructions": instructions,
            "prompts": prompts,
            "used_skills": sorted(self.skill_lookup.keys()),
            "skill_dir": rel(self.skill_dir_path(target)),
        }

    def skill_description(
        self, source: Source, header: dict[str, str], body: str
    ) -> str:
        title = first_heading(body, public_name(self.prefix, source))
        apply_to = header.get("applyTo")
        if header.get("description"):
            return header["description"]
        if apply_to:
            return f"Use for {self.prefix} repository work involving {title}. Applies to {apply_to}."
        return f"Use for {self.prefix} repository work involving {title}."

    def generated_skill(self, source: Source, target: str, output_path: Path) -> str:
        header, body = split_front_matter(source.path.read_text(encoding="utf-8"))
        header = {
            key: self.render_templates(value, target, output_path)
            for key, value in header.items()
        }
        body = self.render_templates(body, target, output_path).strip()
        name = public_name(self.prefix, source)
        description = self.skill_description(source, header, body)
        return (
            "---\n"
            f"name: {name}\n"
            f"description: {yaml_quote(description)}\n"
            f"{skill_metadata_block(source, output_path.relative_to(self.repo).as_posix())}"
            "---\n"
            "\n"
            f"{body}\n"
        )

    def command_description(
        self, source: Source, header: dict[str, str], body: str
    ) -> str:
        """The `description` for a generated Claude command's front matter.

        Prefer an explicit library `description:`; otherwise fall back to the body's
        first heading (what shows in claude-code-acp's slash-command menu). This is
        the prompt analogue of ``skill_description``.
        """
        if header.get("description"):
            return header["description"]
        return first_heading(body, public_name(self.prefix, source))

    def generated_command(self, source: Source, target: str, output_path: Path) -> str:
        """Render a library prompt into a Claude slash command WITH front matter.

        Without a `description` in the front matter, claude-code-acp has nothing to
        advertise over ACP and the command never appears in Zed's autocomplete. So,
        like ``generated_skill``, we emit a header carrying the slash-command keys the
        parser recognises (description / argument-hint / model / allowed-tools) plus
        the same `metadata:` provenance block skills get. Farrier-internal keys
        (`agent`, `name`) are intentionally dropped: the command name comes from the
        filename, and `agent` only selected the backend at render time.
        """
        header, body = split_front_matter(source.path.read_text(encoding="utf-8"))
        header = {
            key: self.render_templates(value, target, output_path)
            for key, value in header.items()
        }
        body = self.render_templates(body, target, output_path).strip()
        lines = [
            "---",
            f"description: {yaml_quote(self.command_description(source, header, body))}",
        ]
        # Pass through the optional slash-command keys when the library author set
        # them (accepting both kebab and camelCase spellings in the source).
        for key, aliases in (
            ("argument-hint", ("argument-hint", "argumentHint")),
            ("model", ("model",)),
            ("allowed-tools", ("allowed-tools", "allowedTools")),
        ):
            value = next((header[a] for a in aliases if header.get(a)), None)
            if value:
                lines.append(f"{key}: {yaml_quote(value)}")
        dest_rel = output_path.relative_to(self.repo).as_posix()
        lines.append(skill_metadata_block(source, dest_rel).rstrip("\n"))
        lines.append("---")
        return "\n".join(lines) + "\n\n" + f"{body}\n"

    def render(
        self,
        agents: dict[str, bool],
        roots: set[str],
        workflows: set[str],
        workflow_meta: dict[str, str] | None = None,
    ) -> dict[Path, str]:
        outputs: dict[Path, str] = {}

        if agents.get("copilot"):
            for source in self.skills:
                output_path = self.skill_output_path(source.id, "copilot")
                outputs[output_path] = self.generated_skill(source, "copilot", output_path)

            for source in self.prompts:
                output_path = self.prompt_output_path(source.id, "copilot")
                content = self.render_templates(
                    source.path.read_text(encoding="utf-8"), "copilot", output_path
                )
                outputs[output_path] = content

            for root in roots:
                # Presence was validated up front (see the roots check below), so a miss
                # here cannot happen silently; keep the guard for the tests-built Renderer.
                root_hit = find_in_layers("library", "roots", f"{root}.md")
                if root_hit is not None:
                    _root_layer, root_path = root_hit
                    for output_path in [
                        self.repo / ".github" / "copilot-instructions.md",
                        self.repo / ".github" / "agents" / "copilot-instructions.md",
                    ]:
                        content = self.render_templates(
                            root_path.read_text(encoding="utf-8"),
                            "copilot",
                            output_path,
                        )
                        outputs[output_path] = content

        if agents.get("codex"):
            for source in self.skills:
                output_path = self.skill_output_path(source.id, "codex")
                outputs[output_path] = self.generated_skill(
                    source, "codex", output_path
                )
            for source in self.prompts:
                output_path = self.prompt_output_path(source.id, "codex")
                content = self.render_templates(
                    source.path.read_text(encoding="utf-8"), "codex", output_path
                )
                outputs[output_path] = content

        if agents.get("claude"):
            for source in self.skills:
                output_path = self.skill_output_path(source.id, "claude")
                outputs[output_path] = self.generated_skill(
                    source, "claude", output_path
                )
            for source in self.prompts:
                output_path = self.prompt_output_path(source.id, "claude")
                outputs[output_path] = self.generated_command(
                    source, "claude", output_path
                )

        # Workflows are NOT installed/copied — they run directly from whichever library
        # layer holds them (see render_agents_mk: the launcher passes the workflow NAME
        # and workhorse resolves it across the same layers).
        # Validate the selection is known so a typo still fails loudly here.
        unknown_workflows = sorted(
            workflow for workflow in workflows
            if find_in_layers("workflows", workflow) is None
        )
        if unknown_workflows:
            raise SystemExit(
                unknown_selection_error(
                    "workflows",
                    unknown_workflows,
                    available_names("workflows", dirs=True),
                    extra=(
                        "Workflows are not copied into the repo — they run from the library "
                        "layer that holds them, so the name must resolve at install time."
                    ),
                )
            )

        # Same discipline for roots. These render only into the copilot adapter, so an
        # unknown one used to be skipped in silence — and on a repo with copilot disabled it
        # was never even looked at. Validate unconditionally: the declaration is wrong
        # regardless of which assistants happen to be enabled, and finding that out only
        # after switching assistants on is the kind of delayed surprise this check exists
        # to prevent.
        unknown_roots = sorted(
            root for root in roots
            if find_in_layers("library", "roots", f"{root}.md") is None
        )
        if unknown_roots:
            raise SystemExit(
                unknown_selection_error(
                    "roots",
                    unknown_roots,
                    available_names("library", "roots", suffix=".md"),
                    extra=(
                        "Roots render only into the copilot adapter, but the name is "
                        "validated whether or not copilot is enabled — otherwise a bad "
                        "declaration stays dormant until someone switches copilot on."
                    ),
                )
            )

        # The launcher (.agents/agents.mk) is generated for EVERY repo: its
        # agent-install/agent-check targets are useful even with no workflow, and
        # a root Makefile can then include it unconditionally. render_agents_mk
        # only emits the workflow-run targets when >= 1 workflow is installed.
        meta = dict(workflow_meta or {})
        meta.setdefault("repo_url", "REPLACE_ME-git-remote-url")
        meta.setdefault("branch", "main")
        meta.setdefault("agents_dir", DEFAULT_AGENTS_DIR)
        meta.setdefault("repo_name", kebab(self.repo.name))
        meta["agents"] = dict(agents)
        ordered = sorted(workflows)
        outputs[self.repo / LAUNCHER_AGENTS_MK] = render_agents_mk(ordered, meta)

        # The per-repo context manifest + local compose override are what make a
        # run-from-library work, so they are only emitted when a workflow exists.
        if workflows:
            # Emit one manifest per ENABLED assistant so a run can target the matching
            # adapters (instruction_ref → .claude/skills, .github/skills, …). AGENT_CLI
            # selects which at run time (launcher CONTEXT_FILE + workhorse auto-detect).
            enabled_assistants = [
                t for t in ("claude", "codex", "copilot") if agents.get(t)
            ]
            # The primary (first enabled) assistant also backs the generic manifest,
            # for back-compat and workhorse's AGENT_CLI-agnostic auto-detect default.
            manifest_target = enabled_assistants[0] if enabled_assistants else "claude"
            for assistant in enabled_assistants:
                outputs[self.repo / LAUNCHER_CONTEXT_MANIFEST_FMT.format(assistant)] = (
                    json.dumps(
                        self.context_manifest(assistant), indent=2, sort_keys=True
                    )
                    + "\n"
                )
            outputs[self.repo / LAUNCHER_CONTEXT_MANIFEST] = (
                json.dumps(
                    self.context_manifest(manifest_target), indent=2, sort_keys=True
                )
                + "\n"
            )
            outputs[self.repo / LAUNCHER_COMPOSE] = render_local_compose(ordered, meta)

        # Only emit a thin root Makefile when the repo has none — never clobber a
        # user-authored Makefile. When one already exists, the generated launcher
        # is wired into it instead via ensure_makefile_include() at install time
        # (an idempotent include block), so its agent targets are reachable either
        # way. Both paths run regardless of workflows, since the launcher is too.
        root_makefile = self.repo / LAUNCHER_ROOT_MAKEFILE
        if not root_makefile.exists():
            outputs[root_makefile] = (
                "# Thin entrypoint — includes the generated agent launcher.\n"
                "# Generated by vigilant-octo/agents/install.py because this repo had\n"
                "# no root Makefile. Safe to extend with your own targets; the\n"
                "# installer will not overwrite a Makefile once it exists.\n"
                f"include {LAUNCHER_AGENTS_MK}\n"
            )

        return outputs

    def render_local_instruction(
        self,
        skill_names: list[str],
        target: str,
        output_path: Path,
        readme_mode: str = "inline",
    ) -> str:
        parts: list[str] = []
        sources: list[Source] = []
        for skill_name in skill_names:
            source = self.skill_source(skill_name)
            sources.append(source)
            _, body = split_front_matter(source.path.read_text(encoding="utf-8"))
            part = self.render_templates(body, target, output_path).strip()
            if part:
                parts.append(part)
        rendered = "\n\n---\n\n".join(parts)
        # Claude strips block-level HTML comments before loading CLAUDE.md, so the
        # banner never reaches the agent's context; other targets would feed it in.
        banner = ""
        if target == "claude":
            dest_rel = output_path.relative_to(self.repo).as_posix()
            banner = local_instruction_banner(sources, dest_rel)

        readme = output_path.parent / "README.md"
        if readme_mode == "none" or not readme.exists():
            return banner + rendered
        # `import` mode references the sibling README via Claude's `@` import
        # directive, so its content is pulled in by reference instead of being
        # copied into this file (keeps always-loaded files lean, single source
        # of truth). The `@` directive is Claude-specific; other targets fall
        # back to inlining the body.
        if readme_mode == "import" and target == "claude":
            return f"{banner}{rendered}\n\n## Local README\n\n@README.md\n"
        readme_body = self.render_templates(
            readme.read_text(encoding="utf-8"), target, output_path
        )
        return f"{banner}{rendered}\n\n## Local README\n\n{readme_body.strip()}\n"

    def validate_workflow_dependencies(self, workflow_name: str) -> list[str]:
        """Check that a workflow's dependencies are satisfied by selected skills/prompts.

        Returns a list of missing dependencies (empty if all satisfied).
        """
        hit = find_in_layers("workflows", workflow_name)
        if hit is None:
            return []
        _layer, workflow_root = hit
        required_skills, required_prompts = extract_workflow_dependencies(workflow_root)

        missing = []
        for skill in required_skills:
            if not self.optional_skill_source(skill):
                missing.append(
                    f"skill '{skill}' (referenced in {workflow_name} prompts)"
                )
        for prompt in required_prompts:
            if not self.optional_prompt_source(prompt):
                missing.append(
                    f"prompt '{prompt}' (referenced in {workflow_name} prompts)"
                )

        return missing
