"""The ``Renderer`` — stateful rendering of library sources into agent adapters."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml
from jinja2 import Environment, StrictUndefined
from jinja2 import UndefinedError

from farrier.frontmatter import (
    first_heading,
    front_matter_end,
    frontmatter_mapping,
    frontmatter_tags,
    normalize_tags,
    split_front_matter,
)
from farrier.launcher import (
    LAUNCHER_AGENTS_MK,
    LAUNCHER_CONTEXT_MANIFEST,
    LAUNCHER_CONTEXT_MANIFEST_FMT,
    LAUNCHER_ROOT_MAKEFILE,
    render_agents_mk,
)
from farrier.layers import available_names, find_in_layers
from farrier.naming import relative_reference, repo_prefix, yaml_quote
from farrier.selection_errors import unknown_selection_error
from farrier.sources import (
    Asset,
    Source,
    build_lookup,
    build_policy_lookup,
    library_path,
    library_source_path,
    public_id,
    public_name,
    skill_assets,
)


class Rendered(str):
    """A generated file's text, plus how it must be written."""

    executable: bool = False
    verbatim: bool = False
    assumed: bool = False
    sources: tuple[str, ...] = ()
    parts: tuple[tuple[str, str], ...] = ()

    def __new__(
        cls,
        text: str,
        *,
        executable: bool = False,
        verbatim: bool = False,
        assumed: bool = False,
        sources: tuple[str, ...] = (),
        parts: tuple[tuple[str, str], ...] = (),
    ):
        rendered = super().__new__(cls, text)
        rendered.executable = executable
        rendered.verbatim = verbatim
        rendered.assumed = assumed
        rendered.sources = sources
        rendered.parts = parts
        return rendered


def skill_metadata_block(
    source: Source,
    dest_rel: str,
    tags: list[str] | None = None,
    regenerate: str = "make agent-install",
) -> str:
    """The `metadata:` block stamping a generated skill/command with its source."""
    do_not_edit = (
        "generated — run the `resolve` command below for this machine's editable "
        f"source path, edit that, then `{regenerate}` to regenerate"
    )
    tag_line = f"  tags: [{', '.join(tags)}]\n" if tags else ""
    return (
        "metadata:\n"
        "  generated_by: farrier\n"
        f"  source: {library_source_path(source)}\n"
        f"  resolve: {yaml_quote(f'farrier source {dest_rel}')}\n"
        f"  do_not_edit: {yaml_quote(do_not_edit)}\n"
        f"{tag_line}"
    )


def local_instruction_banner(sources: list[Source], dest_rel: str) -> str:
    """The DO-NOT-EDIT comment prepended to generated Claude instruction files."""
    source_lines = "\n".join(f"  {library_source_path(s)}" for s in sources)
    return (
        "<!--\n"
        "DO NOT EDIT — generated by farrier from the agent library.\n"
        "Edits here are overwritten by `make agent-install` (or: farrier --repo .).\n"
        "Edit the library source(s) instead, then regenerate:\n"
        f"{source_lines}\n"
        f"Editable paths on this machine: `farrier source {dest_rel}`\n"
        "Skill→path mapping: agents.yml → localInstructions\n"
        "-->\n\n"
    )


def asset_banner(
    asset: Asset,
    dest_rel: str,
    overwritten_by: str = "`make agent-install` (or: farrier --repo .)",
) -> str:
    """The DO-NOT-EDIT comment prepended to a generated markdown reference."""
    return (
        "<!--\n"
        "DO NOT EDIT — generated by farrier from the agent library.\n"
        f"Edits here are overwritten by {overwritten_by}.\n"
        "Edit the library source instead, then regenerate:\n"
        f"  {library_path(asset.path, asset.rel)}\n"
        f"Editable path on this machine: `farrier source {dest_rel}`\n"
        "-->\n\n"
    )


def root_banner(source_rel: str, dest_rel: str) -> str:
    """The DO-NOT-EDIT comment prepended to a generated root instruction file."""
    return (
        "<!--\n"
        "DO NOT EDIT \u2014 generated by farrier from the agent library.\n"
        "Edits here are overwritten by `make agent-install` (or: farrier --repo .).\n"
        "Edit the library source instead, then regenerate:\n"
        f"  {source_rel}\n"
        f"Editable path on this machine: `farrier source {dest_rel}`\n"
        "-->\n\n"
    )


def with_banner(text: str, banner: str) -> str:
    """*text* with *banner* spliced in after its front matter, or at the very top."""
    at = front_matter_end(text)
    if at == 0:
        return banner + text
    lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    rest = "\n".join(lines[at:]).removeprefix("\n")
    return "\n".join(lines[:at]) + "\n" + banner + rest


def read_asset_text(asset: Asset) -> str:
    """A bundled asset's text, with a decodable error message when it is not text."""
    try:
        return asset.path.read_text(encoding="utf-8")
    except UnicodeDecodeError as exc:
        raise SystemExit(
            f"error: bundled asset {asset.path} is not UTF-8 text. Skill assets are "
            "rendered and diffed as text; keep binaries out of references/ and "
            "scripts/ (fetch or generate them at run time instead)."
        ) from exc


def strip_arguments_placeholder(body: str) -> str:
    """Drop a command's ``$ARGUMENTS`` line when its body is aggregated instead."""
    lines = [line for line in body.splitlines() if line.strip() != "$ARGUMENTS"]
    return "\n".join(lines)


USER_HARNESS_DIRS = {
    "claude": ".claude",
    "codex": ".codex",
    "copilot": ".copilot",
}


def user_harness_dir(target: str) -> str:
    if target not in USER_HARNESS_DIRS:
        raise SystemExit(f"Unknown user-scope render target: {target}")
    return USER_HARNESS_DIRS[target]


class Renderer:
    def __init__(
        self,
        repo: Path,
        prefix: str,
        repo_config: dict[str, Any],
        template_values: dict[str, Any],
        skills: list[Source],
        prompts: list[Source],
        policies: list[Source] | None = None,
        scope: str = "repo",
    ):
        self.repo = repo
        self.scope = scope
        self.regenerate = "make agent-install" if scope == "repo" else "farrier install --user"
        self.overwritten_by = (
            "`make agent-install` (or: farrier --repo .)"
            if scope == "repo"
            else "`farrier install --user`"
        )
        self.prefix = prefix
        self.repo_context = dict(repo_config)
        self.repo_context["name"] = repo_prefix(repo)
        self.repo_context["prefix"] = prefix
        self.repo_context["root"] = repo.as_posix()
        self.template_values = template_values
        self.skills = skills
        self.prompts = prompts
        self.skill_lookup = build_lookup(skills, prefix)
        self.prompt_lookup = build_lookup(prompts, prefix)
        self.policies = list(policies or [])
        self.policy_lookup = build_policy_lookup(self.policies)
        self._tags: dict[Path, list[str]] = {}

    def dest_rel(self, output_path: Path) -> str:
        """*output_path* as the generated file names itself, for `farrier source`."""
        rel = output_path.relative_to(self.repo).as_posix()
        return f"~/{rel}" if self.scope == "user" else rel

    def skill_tags(self, source: Source) -> list[str]:
        """The `tags:` a library skill declares."""
        cached = self._tags.get(source.path)
        if cached is None:
            cached = frontmatter_tags(source.path.read_text(encoding="utf-8"))
            self._tags[source.path] = cached
        return cached

    def skills_with_tags(self, tags: list[str]) -> list[Source]:
        """The selected skills carrying **all** of *tags*, in library order."""
        wanted = set(tags)
        if not wanted:
            return []
        return [s for s in self.skills if wanted <= set(self.skill_tags(s))]

    def skill_source(self, name: str) -> Source:
        source = self.optional_skill_source(name)
        if source is None:
            raise SystemExit(f"Unknown selected skill reference: {name}")
        return source

    def optional_skill_source(self, name: str) -> Source | None:
        key = name.replace(".", "-")
        source = self.skill_lookup.get(key)
        if source is None and self.prefix and not key.startswith(f"{self.prefix}-"):
            source = self.skill_lookup.get(f"{self.prefix}-{key}")
        return source

    def policy_source(self, name: str) -> Source:
        """The library file a ``policies:`` entry names, or exit."""
        key = name.replace(".", "-")
        source = self.policy_lookup.get(key)
        if source is None:
            available = sorted({public_id(s) for s in self.policies})
            catalog = (
                "Available policies: " + ", ".join(available)
                if available
                else "The library layers hold no policies at all."
            )
            raise SystemExit(f"Unknown policy reference: {name}. {catalog}")
        return source

    def prompt_source(self, name: str) -> Source:
        key = name.replace(".", "-")
        if key not in self.prompt_lookup:
            raise SystemExit(f"Unknown selected prompt reference: {name}")
        return self.prompt_lookup[key]

    def optional_prompt_source(self, name: str) -> Source | None:
        return self.prompt_lookup.get(name.replace(".", "-"))

    def skill_output_path(self, name: str, target: str) -> Path:
        source = self.skill_source(name)
        generated = public_name(self.prefix, source)
        if self.scope == "user":
            return (
                self.repo / user_harness_dir(target) / "skills" / generated / "SKILL.md"
            )
        if target == "copilot":
            return self.repo / ".github" / "skills" / generated / "SKILL.md"
        if target == "codex":
            return self.repo / ".agents" / "skills" / generated / "SKILL.md"
        if target == "claude":
            return self.repo / ".claude" / "skills" / generated / "SKILL.md"
        raise SystemExit(f"Unknown skill render target: {target}")

    def prompt_output_path(self, name: str, target: str) -> Path:
        source = self.prompt_source(name)
        generated = public_name(self.prefix, source)
        if self.scope == "user":
            if target != "claude":
                raise SystemExit(
                    f"{target} has no user-scope prompt directory — prompts are "
                    "Claude-only at user scope."
                )
            return self.repo / ".claude" / "commands" / f"{generated}.md"
        if target == "copilot":
            return self.repo / ".github" / "prompts" / f"{generated}.prompt.md"
        if target == "codex":
            return self.repo / ".agents" / "prompts" / f"{generated}.prompt.md"
        if target == "claude":
            return self.repo / ".claude" / "commands" / f"{generated}.md"
        raise SystemExit(f"Unknown prompt render target: {target}")

    def skill_dir_path(self, target: str) -> Path:
        if self.scope == "user":
            return self.repo / user_harness_dir(target) / "skills"
        if target == "copilot":
            return self.repo / ".github" / "skills"
        if target == "codex":
            return self.repo / ".agents" / "skills"
        if target == "claude":
            return self.repo / ".claude" / "skills"
        raise SystemExit(f"Unknown skill dir target: {target}")

    def render_templates(self, content: str, target: str, from_file: Path) -> str:
        if not any(
            token in content
            for token in [
                "{%",
                "instruction_file(",
                "instruction_ref(",
                "skill_file(",
                "prompt_file(",
                "prompt_ref(",
                "find_by_tags(",
                "skill_dir(",
                "isUsingInstruction(",
                "repo.",
                "template.",
                "vars.",
            ]
        ):
            return content
        env = Environment(autoescape=False, undefined=StrictUndefined)
        template = env.from_string(content)

        def instruction_ref(name: str) -> str:
            if self.optional_skill_source(name):
                return relative_reference(
                    from_file, self.skill_output_path(name, target)
                )
            return f"generated {name} instruction file when installed"

        def prompt_ref(name: str) -> str:
            if self.optional_prompt_source(name):
                return relative_reference(
                    from_file, self.prompt_output_path(name, target)
                )
            return f"generated {name} prompt when installed"

        def skill_file(name: str) -> str:
            if self.optional_skill_source(name):
                return relative_reference(
                    from_file, self.skill_output_path(name, target)
                )
            return f"generated {name} skill when installed"

        def prompt_file_fn(name: str) -> str:
            if self.optional_prompt_source(name):
                return relative_reference(
                    from_file, self.prompt_output_path(name, target)
                )
            return f"generated {name} prompt when installed"

        def is_using_instruction(instruction_name: str) -> bool:
            """Check if this project has a specific instruction selected."""
            return self.optional_skill_source(instruction_name) is not None

        def find_by_tags(*tags: str) -> str:
            """The installed skills tagged with all of *tags*, as a reference list."""
            wanted = normalize_tags(list(tags))
            refs = sorted(
                relative_reference(
                    from_file, self.skill_output_path(source.id, target)
                )
                for source in self.skills_with_tags(wanted)
            )
            return ", ".join(f"`{ref}`" for ref in refs)

        def workhorse_var(name: str) -> str:
            """Emit a runtime variable reference that workhorse will fill at run time."""
            return "{{ " + name + " }}"

        repo_context: Any = (
            self.repo_context
            if self.scope == "repo"
            else StrictUndefined(
                hint="`repo.…` has no value at user scope — a user-scope skill is "
                     "installed once for every project, so there is no repo to name."
            )
        )
        try:
            return template.render(
                instruction_file=lambda name: (
                    relative_reference(
                        from_file, self.skill_output_path(name, target)
                    )
                    if self.optional_skill_source(name)
                    else f"generated {name} instruction file when installed"
                ),
                instruction_ref=instruction_ref,
                skill_file=skill_file,
                prompt_file=prompt_file_fn,
                prompt_ref=prompt_ref,
                skill_dir=lambda: relative_reference(
                    from_file, self.skill_dir_path(target)
                ),
                isUsingInstruction=is_using_instruction,
                find_by_tags=find_by_tags,
                workhorse_var=workhorse_var,
                repo=repo_context,
                template=self.template_values,
                vars=self.template_values,
                target=target,
            )
        except UndefinedError as exc:
            raise SystemExit(
                f"error: {from_file.name} references a template value that is not "
                f"defined: {exc.message}\n"
                "Define it under `vars:` in agents.yml, or under "
                "`[user_library.template]` for a user-scope install — or guard the "
                'reference in the library source with `| default("…")`.'
            ) from exc

    def context_manifest(self, target: str) -> dict[str, Any]:
        """Per-repo manifest consumed by workhorse at run time (see workhorse/templates.py)."""
        def rel(path: Path) -> str:
            return path.relative_to(self.repo).as_posix()

        instructions = {
            key: rel(self.skill_output_path(source.id, target))
            for key, source in self.skill_lookup.items()
        }
        prompts = {
            key: rel(self.prompt_output_path(source.id, target))
            for key, source in self.prompt_lookup.items()
        }
        instruction_tags = {
            key: tags
            for key, source in self.skill_lookup.items()
            if (tags := self.skill_tags(source))
        }
        repo_context = {**self.repo_context, "root": "."}
        return {
            "template": self.template_values,
            "repo": repo_context,
            "vars": self.template_values,
            "instructions": instructions,
            "instruction_tags": instruction_tags,
            "prompts": prompts,
            "used_skills": sorted(self.skill_lookup.keys()),
            "skill_dir": rel(self.skill_dir_path(target)),
        }

    def skill_description(
        self, source: Source, header: dict[str, str], body: str
    ) -> str:
        title = first_heading(body, public_name(self.prefix, source))
        apply_to = header.get("applyTo")
        if header.get("description"):
            return header["description"]
        if apply_to:
            return f"Use for {self.prefix} repository work involving {title}. Applies to {apply_to}."
        return f"Use for {self.prefix} repository work involving {title}."

    def generated_skill(self, source: Source, target: str, output_path: Path) -> str:
        header, body = split_front_matter(source.path.read_text(encoding="utf-8"))
        header = {
            key: self.render_templates(value, target, output_path)
            for key, value in header.items()
        }
        body = self.render_templates(body, target, output_path).strip()
        name = public_name(self.prefix, source)
        description = self.skill_description(source, header, body)
        dest_rel = self.dest_rel(output_path)
        return (
            "---\n"
            f"name: {name}\n"
            f"description: {yaml_quote(description)}\n"
            f"{skill_metadata_block(source, dest_rel, self.skill_tags(source), self.regenerate)}"
            "---\n"
            "\n"
            f"{body}\n"
        )

    def generated_assets(
        self, source: Source, target: str, skill_path: Path
    ) -> dict[Path, Rendered]:
        """The files bundled with *source*, keyed by where they install."""
        if skill_path.name != "SKILL.md":
            raise SystemExit(
                f"Cannot render bundled assets into the flat {target!r} layout "
                f"({skill_path.name}) — skill assets need a per-skill directory."
            )
        outputs: dict[Path, Rendered] = {}
        for asset in skill_assets(source):
            output_path = skill_path.parent / asset.rel
            text = read_asset_text(asset)
            if asset.is_script or asset.path.suffix != ".md":
                outputs[output_path] = Rendered(
                    text, executable=asset.is_script, verbatim=True
                )
                continue
            dest_rel = self.dest_rel(output_path)
            body = self.render_templates(text, target, output_path).strip()
            outputs[output_path] = Rendered(
                asset_banner(asset, dest_rel, self.overwritten_by) + body + "\n"
            )
        return outputs

    def command_description(
        self, source: Source, header: dict[str, str], body: str
    ) -> str:
        """The `description` for a generated Claude command's front matter."""
        if header.get("description"):
            return header["description"]
        return first_heading(body, public_name(self.prefix, source))

    def generated_command(self, source: Source, target: str, output_path: Path) -> str:
        """Render a library prompt with target-specific fields and shared provenance."""
        header, body = split_front_matter(source.path.read_text(encoding="utf-8"))
        header = {
            key: self.render_templates(value, target, output_path)
            for key, value in header.items()
        }
        body = self.render_templates(body, target, output_path).strip()
        if target == "copilot":
            rendered = self.render_templates(
                source.path.read_text(encoding="utf-8"), target, output_path
            )
            native_header = frontmatter_mapping(rendered)
            native_header.pop("metadata", None)
            native_header["description"] = self.command_description(source, header, body)
            lines = ["---", yaml.safe_dump(
                native_header, sort_keys=False, allow_unicode=True
            ).rstrip("\n")]
        else:
            lines = [
                "---",
                f"description: {yaml_quote(self.command_description(source, header, body))}",
            ]
            for key, aliases in (
                ("argument-hint", ("argument-hint", "argumentHint")),
                ("model", ("model",)),
                ("allowed-tools", ("allowed-tools", "allowedTools")),
            ):
                value = next((header[a] for a in aliases if header.get(a)), None)
                if value:
                    lines.append(f"{key}: {yaml_quote(value)}")
        dest_rel = self.dest_rel(output_path)
        lines.append(
            skill_metadata_block(
                source, dest_rel, self.skill_tags(source), self.regenerate
            ).rstrip("\n")
        )
        lines.append("---")
        return "\n".join(lines) + "\n\n" + f"{body}\n"

    def render(
        self,
        agents: dict[str, bool],
        roots: set[str],
    ) -> dict[Path, str]:
        outputs: dict[Path, str] = {}

        def render_skills(target: str) -> None:
            """Every selected skill into *target*, each with its bundled assets."""
            for source in self.skills:
                output_path = self.skill_output_path(source.id, target)
                outputs[output_path] = self.generated_skill(source, target, output_path)
                outputs.update(self.generated_assets(source, target, output_path))

        if agents.get("copilot"):
            render_skills("copilot")

            for source in self.prompts:
                output_path = self.prompt_output_path(source.id, "copilot")
                outputs[output_path] = self.generated_command(
                    source, "copilot", output_path
                )

            for root in roots:
                root_hit = find_in_layers("library", "roots", f"{root}.md")
                if root_hit is not None:
                    _root_layer, root_path = root_hit
                    source_rel = library_path(root_path, f"roots/{root}.md")
                    for output_path in [
                        self.repo / ".github" / "copilot-instructions.md",
                        self.repo / ".github" / "agents" / "copilot-instructions.md",
                    ]:
                        content = self.render_templates(
                            root_path.read_text(encoding="utf-8"),
                            "copilot",
                            output_path,
                        )
                        dest_rel = output_path.relative_to(self.repo).as_posix()
                        outputs[output_path] = with_banner(
                            content, root_banner(source_rel, dest_rel)
                        )

        if agents.get("codex"):
            render_skills("codex")
            for source in self.prompts:
                output_path = self.prompt_output_path(source.id, "codex")
                outputs[output_path] = self.generated_command(
                    source, "codex", output_path
                )

        if agents.get("claude"):
            render_skills("claude")
            for source in self.prompts:
                output_path = self.prompt_output_path(source.id, "claude")
                outputs[output_path] = self.generated_command(
                    source, "claude", output_path
                )

        unknown_roots = sorted(
            root for root in roots
            if find_in_layers("library", "roots", f"{root}.md") is None
        )
        if unknown_roots:
            raise SystemExit(
                unknown_selection_error(
                    "roots",
                    unknown_roots,
                    available_names("library", "roots", suffix=".md"),
                    extra=(
                        "Roots render only into the copilot adapter, but the name is "
                        "validated whether or not copilot is enabled — otherwise a bad "
                        "declaration stays dormant until someone switches copilot on."
                    ),
                )
            )

        if self.scope == "user":
            return outputs

        outputs[self.repo / LAUNCHER_AGENTS_MK] = render_agents_mk()

        enabled_assistants = [t for t in ("claude", "codex", "copilot") if agents.get(t)]
        manifest_target = enabled_assistants[0] if enabled_assistants else "claude"
        for assistant in enabled_assistants:
            outputs[self.repo / LAUNCHER_CONTEXT_MANIFEST_FMT.format(assistant)] = (
                json.dumps(self.context_manifest(assistant), indent=2, sort_keys=True)
                + "\n"
            )
        outputs[self.repo / LAUNCHER_CONTEXT_MANIFEST] = (
            json.dumps(self.context_manifest(manifest_target), indent=2, sort_keys=True)
            + "\n"
        )

        root_makefile = self.repo / LAUNCHER_ROOT_MAKEFILE
        if not root_makefile.exists():
            outputs[root_makefile] = (
                "# Thin entrypoint — includes the generated agent launcher.\n"
                "# Generated by farrier because this repo had\n"
                "# no root Makefile. Safe to extend with your own targets; the\n"
                "# installer will not overwrite a Makefile once it exists.\n"
                f"include {LAUNCHER_AGENTS_MK}\n"
            )

        return outputs

    def instruction_sources(
        self,
        skill_names: list[str],
        prompt_names: list[str] | None = None,
        policy_names: list[str] | None = None,
    ) -> list[Source]:
        """The library files one localInstructions mapping aggregates, in order."""
        return (
            [self.policy_source(name) for name in policy_names or []]
            + [self.skill_source(name) for name in skill_names]
            + [self.prompt_source(name) for name in prompt_names or []]
        )

    def render_local_instruction(
        self,
        skill_names: list[str],
        target: str,
        output_path: Path,
        include_readme: bool = True,
        prompt_names: list[str] | None = None,
        policy_names: list[str] | None = None,
    ) -> str:
        """The aggregated AGENTS.md for one localInstructions mapping."""
        parts: list[tuple[str, str]] = []
        for source in self.instruction_sources(skill_names, prompt_names, policy_names):
            _, body = split_front_matter(source.path.read_text(encoding="utf-8"))
            if source.kind == "prompt":
                body = strip_arguments_placeholder(body)
            part = self.render_templates(body, target, output_path).strip()
            if part:
                parts.append((library_source_path(source), part))
        rendered = "\n\n---\n\n".join(part for _, part in parts)

        readme = output_path.parent / "README.md"
        if include_readme and readme.exists():
            readme_body = self.render_templates(
                readme.read_text(encoding="utf-8"), target, output_path
            )
            rendered = f"{rendered}\n\n## Local README\n\n{readme_body.strip()}\n"
        return Rendered(
            rendered,
            assumed=True,
            sources=tuple(rel for rel, _ in parts),
            parts=tuple(parts),
        )

    def render_claude_pointer(
        self,
        skill_names: list[str],
        output_path: Path,
        prompt_names: list[str] | None = None,
        readme_import: bool = False,
        policy_names: list[str] | None = None,
    ) -> str:
        """The CLAUDE.md that points Claude at the AGENTS.md beside it."""
        sources = self.instruction_sources(skill_names, prompt_names, policy_names)
        dest_rel = output_path.relative_to(self.repo).as_posix()
        banner = local_instruction_banner(sources, dest_rel)
        readme = "\n@README.md\n" if readme_import else ""
        return Rendered(
            f"{banner}@AGENTS.md\n{readme}",
            sources=tuple(library_source_path(source) for source in sources),
        )
