"""Workflow metadata, dependency extraction, and generated-file headers.

Resolving the launcher's repo/branch/agents-dir meta, scanning a workflow's prompts
for the skills/prompts it references, and stamping DO-NOT-EDIT headers.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from farrier.git import get_default_branch, get_git_remote
from farrier.launcher import DEFAULT_AGENTS_DIR


WORKFLOW_SKIP_PARTS = {
    "__pycache__",
    ".runs",
    ".state",
    ".codex-home",
}


def collect_template_values(config: dict[str, Any]) -> dict[str, Any]:
    values: dict[str, Any] = {}
    for key in ["vars", "template"]:
        configured = config.get(key) or {}
        if not isinstance(configured, dict):
            raise SystemExit(f"{key} must be a YAML mapping when present")
        values.update(configured)
    return values


def resolve_workflow_meta(
    config: dict[str, Any], repo: Path, repo_name: str
) -> dict[str, Any]:
    """Resolve repo_url / branch / agents-dir for the launcher scaffolding.

    Precedence: explicit `agents.yml` `workflow:` block, then the repo's own
    git origin + DEFAULT branch (master/main — NOT the branch currently checked
    out), then a clearly-marked placeholder. REPO_BRANCH is the trunk the worker
    clones and the coder workflow targets/merges PRs into, so it must be the
    long-lived integration branch, not the install-time HEAD. An explicit repo URL
    selects authenticated remote checkout; otherwise local runs clone a read-only
    bind mount of the host repository.
    """
    workflow_cfg = config.get("workflow") or {}
    if not isinstance(workflow_cfg, dict):
        raise SystemExit("workflow must be a YAML mapping when present")

    repo_url = workflow_cfg.get("repoUrl") or workflow_cfg.get("repo_url")
    remote_checkout = bool(repo_url)
    branch = workflow_cfg.get("branch")
    agents_dir = workflow_cfg.get("agentsDir") or workflow_cfg.get("agents_dir")
    # Host env vars to forward into the Docker run (interpolated from the local
    # env at `docker compose up` time). E.g. a GitHub token for opening PRs.
    env_passthrough = (
        workflow_cfg.get("envPassthrough") or workflow_cfg.get("env_passthrough") or []
    )
    if not isinstance(env_passthrough, list):
        raise SystemExit("workflow.envPassthrough must be a list of env var names")
    env_passthrough = [str(name) for name in env_passthrough]
    if not repo_url:
        repo_url = get_git_remote(repo)
    if not branch:
        branch = get_default_branch(repo)

    return {
        "repo_url": str(repo_url) if repo_url else "REPLACE_ME-git-remote-url",
        "branch": str(branch) if branch else "main",
        "agents_dir": str(agents_dir) if agents_dir else DEFAULT_AGENTS_DIR,
        "repo_name": repo_name,
        "env_passthrough": env_passthrough,
        "remote_checkout": remote_checkout,
    }


def should_skip_workflow_file(path: Path, root: Path) -> bool:
    rel = path.relative_to(root)
    return (
        any(part in WORKFLOW_SKIP_PARTS for part in rel.parts) or path.suffix == ".pyc"
    )


def extract_workflow_dependencies(workflow_root: Path) -> tuple[set[str], set[str]]:
    """Extract skill and prompt names referenced in workflow prompts via instruction_ref/prompt_ref.

    Returns: (skill_names, prompt_names)
    """
    skills = set()
    prompts = set()

    prompts_dir = workflow_root / "prompts"
    if not prompts_dir.exists():
        return skills, prompts

    for prompt_file in prompts_dir.glob("*.md"):
        content = prompt_file.read_text(encoding="utf-8")

        # Find all instruction_ref("name") calls
        for match in re.finditer(r'instruction_ref\("([^"]+)"\)', content):
            skills.add(match.group(1))

        # Find all prompt_ref("name") calls
        for match in re.finditer(r'prompt_ref\("([^"]+)"\)', content):
            prompts.add(match.group(1))

    return skills, prompts


# File suffixes that accept a `#`-style comment header.
_COMMENTABLE_SUFFIXES = {".py", ".sh", ".yaml", ".yml"}


def _prepend_workflow_header(content: str, source: Path, rel_in_workflow: str) -> str:
    """Prepend a DO-NOT-EDIT comment to a generated workflow file.

    Shebang lines are preserved as the first line. `.md` and `.json` files
    (and any other non-commentable type) are returned unchanged.
    """
    if source.suffix.lower() not in _COMMENTABLE_SUFFIXES:
        return content
    header = (
        f"# DO NOT EDIT — generated by farrier from the agent library.\n"
        f"# Canonical source: `farrier config show library_dir` → workflows/{rel_in_workflow}\n"
        f"# Regenerate      : make agent-install  (or: farrier --repo .)\n"
    )
    first, _, rest = content.partition("\n")
    if first.startswith("#!"):
        return first + "\n" + header + "\n" + rest
    return header + "\n" + content


def _workflow_claude_md(workflow: str) -> str:
    """Generate the CLAUDE.md dropped into each installed workflow directory."""
    return f"""\
# DO NOT EDIT — generated by farrier

All files in this directory are installed by **farrier** from the agent library.
Edits made here will be **overwritten** the next time `make agent-install` (or `farrier --repo .`) runs.

## Finding the canonical source

```
farrier config show | grep library_dir
```

The canonical source for this workflow is at `<library_dir>/workflows/{workflow}/`.

## Regenerating after an upstream change

```
farrier --repo .
```
"""
