"""Agent reply models and node return models for the coder workflow."""
from __future__ import annotations

from workhorse_workflows.coder.shared.schemas._base import CoderResult
from workhorse_workflows.coder.shared.schemas.backlog import (
    FixPick,
    FixPruned,
    FixStorySeed,
)
from workhorse_workflows.coder.shared.schemas.ci import (
    CiChecks,
    CiRepoPick,
    FixCiResult,
    PushOutcome,
)
from workhorse_workflows.coder.shared.schemas.dev import (
    BranchOutcome,
    ChangedFiles,
    DispatchEntry,
    FailureReport,
    GateList,
    GateOutcome,
    ImplContext,
    ImplResult,
    ImplStatus,
    OperatorAnswer,
    OperatorResolution,
    PlanFields,
    PlanService,
    PlanSummary,
    PlanValidation,
    QaRunEntry,
)
from workhorse_workflows.coder.shared.schemas.docs import (
    ContextClassification,
    DocsResult,
    DocumentationGate,
    DocumentationResult,
    OkfDetection,
)
from workhorse_workflows.coder.shared.schemas.genesis import (
    AgentsYml,
    FarrierInstall,
    GenesisReport,
    GitInit,
    Skeleton,
    TargetClassification,
)
from workhorse_workflows.coder.shared.schemas.okf import OkfContextResult
from workhorse_workflows.coder.shared.schemas.pr import (
    MergeFixResult,
    MergeFlagged,
    MergeOutcome,
    PrGate,
    StoryPr,
)
from workhorse_workflows.coder.shared.schemas.qa import (
    BacklogDrain,
    FailureAttribution,
    QaCleared,
    QaFlowResult,
    QaPlanRun,
    QaPlanValidation,
    QaResult,
    QaRunResult,
    RegressionSuite,
    RegressionSuites,
    RegressionRun,
    ScreenshotFlush,
    StackStatus,
)
from workhorse_workflows.coder.shared.schemas.queue import (
    BaseBranch,
    EpicBranch,
    EpicPruned,
    LaunchEntry,
    LaunchSet,
    ReplanResult,
    StoryBranch,
    StoryCommitted,
    StoryStamped,
    WorktreeCleanliness,
)
from workhorse_workflows.coder.shared.schemas.review import (
    Feedback,
    ReviewContext,
    ReviewFinding,
)
from workhorse_workflows.coder.shared.schemas.story import SpecsStamped, StoryPaths, WorkspaceDirs

__all__ = [
    "AgentsYml",
    "BacklogDrain",
    "BaseBranch",
    "BranchOutcome",
    "CiChecks",
    "ChangedFiles",
    "CiRepoPick",
    "CoderResult",
    "ContextClassification",
    "DispatchEntry",
    "DocsResult",
    "DocumentationGate",
    "DocumentationResult",
    "EpicBranch",
    "EpicPruned",
    "LaunchEntry",
    "LaunchSet",
    "FailureAttribution",
    "FailureReport",
    "FarrierInstall",
    "Feedback",
    "FixCiResult",
    "FixPick",
    "FixPruned",
    "FixStorySeed",
    "GenesisReport",
    "GitInit",
    "GateList",
    "GateOutcome",
    "ImplContext",
    "ImplResult",
    "ImplStatus",
    "MergeFixResult",
    "MergeFlagged",
    "MergeOutcome",
    "OkfContextResult",
    "OkfDetection",
    "OperatorAnswer",
    "OperatorResolution",
    "PlanFields",
    "PlanService",
    "PlanSummary",
    "PlanValidation",
    "PrGate",
    "PushOutcome",
    "QaCleared",
    "ReplanResult",
    "QaFlowResult",
    "QaPlanRun",
    "QaPlanValidation",
    "QaResult",
    "QaRunEntry",
    "QaRunResult",
    "RegressionSuite",
    "RegressionSuites",
    "RegressionRun",
    "ReviewContext",
    "ReviewFinding",
    "ScreenshotFlush",
    "Skeleton",
    "SpecsStamped",
    "StackStatus",
    "StoryBranch",
    "StoryCommitted",
    "StoryPaths",
    "StoryPr",
    "StoryStamped",
    "TargetClassification",
    "WorkspaceDirs",
    "WorktreeCleanliness",
]
