"""Front matter, banners and headings come from the parser, not from a regex over raw text.

Each case here is something the three regexes and the `line.split(":", 1)` loop they
replaced got wrong. See the `stablemate-structured-parsing` skill.
"""
from __future__ import annotations

from farrier.frontmatter import (
    banner_sources,
    first_heading,
    frontmatter_metadata,
    frontmatter_tags,
    split_front_matter,
)

BANNER = (
    "<!--\n"
    "DO NOT EDIT — generated by farrier from the agent library.\n"
    "Edit the library source(s) instead, then regenerate:\n"
    "  library/skills/acme/a/SKILL.md\n"
    "  library/skills/acme/b/SKILL.md\n"
    "-->\n\n"
    "# Doc\n\n"
    "Prose that mentions library/skills/acme/c/SKILL.md and must not be provenance.\n"
)


def test_banner_sources_stop_at_the_end_of_the_banner():
    assert banner_sources(BANNER) == [
        "library/skills/acme/a/SKILL.md",
        "library/skills/acme/b/SKILL.md",
    ]


def test_banner_sources_survive_crlf():
    """The regex anchored on `\\A<!--\\n`, so a CRLF file reported no provenance at all."""
    assert banner_sources(BANNER.replace("\n", "\r\n")) == [
        "library/skills/acme/a/SKILL.md",
        "library/skills/acme/b/SKILL.md",
    ]


def test_a_file_without_a_farrier_banner_has_no_sources():
    assert banner_sources("<!--\njust a comment\n-->\n\n# Doc\n") == []
    assert banner_sources("# Doc\n") == []


def test_folded_description_is_read():
    """`description: >` gave the line splitter an empty string — a skill with no description."""
    header, _body = split_front_matter(
        "---\nname: acme-thing\ndescription: >\n  A folded description\n  over two lines.\n---\n\nbody\n"
    )
    assert header["description"] == "A folded description over two lines.\n"


def test_a_value_containing_a_colon_is_not_truncated():
    header, _ = split_front_matter('---\ndescription: "Use for a: b work"\n---\n\nbody\n')
    assert header["description"] == "Use for a: b work"


def test_nested_metadata_does_not_leak_top_level_keys():
    """The line splitter read `  source: x` as a top-level key named `source`."""
    header, _ = split_front_matter(
        "---\nname: n\nmetadata:\n  source: library/skills/acme/a/SKILL.md\n---\n\nbody\n"
    )
    assert sorted(header) == ["metadata", "name"]


def test_a_list_value_keeps_its_flow_spelling():
    header, _ = split_front_matter("---\nallowed-tools: [Bash, Read]\n---\n\nbody\n")
    assert header["allowed-tools"] == "[Bash, Read]"


def test_body_drops_exactly_one_separator_line():
    _, body = split_front_matter("---\nname: n\n---\n\n# Title\n\nbody\n")
    assert body == "# Title\n\nbody\n"


def test_front_matter_survives_crlf_and_a_missing_trailing_newline():
    header, body = split_front_matter("---\r\nname: n\r\n---\r\n\r\nbody\r\n")
    assert header == {"name": "n"} and body == "body\n"
    header, body = split_front_matter("---\nname: n\n---")
    assert header == {"name": "n"} and body == ""


def test_tags_and_metadata_read_the_same_block_as_split():
    text = "---\nname: n\ntags: [Go, testing]\nmetadata:\n  source: library/x\n---\n\nbody\n"
    assert frontmatter_tags(text) == ["go", "testing"]
    assert frontmatter_metadata(text) == {"source": "library/x"}


def test_first_heading_ignores_a_heading_inside_a_fence():
    """A skill whose first fence shows markdown used to be titled by the sample."""
    body = "Intro prose.\n\n```markdown\n# Not the title\n```\n\n# The Title\n"
    assert first_heading(body, "fallback") == "The Title"


def test_first_heading_falls_back_when_there_is_none():
    assert first_heading("just prose\n", "fallback") == "fallback"
