"""`localInstructions` aggregation: which sources go in, and what the file is called.

An entry names skills (`skill`/`skills`), prompts (`prompt`/`prompts`), or both —
prompts are there so a procedure a repo wants *always loaded* stays one library
file rather than a hand-maintained fragment in every consuming repo's root
instructions. `filename` picks the single output name, which is how a
claude-only repo generates AGENTS.md without turning the codex adapter on.

    ./.venv/bin/python -m pytest tests/test_local_instruction_mapping.py
"""
from __future__ import annotations

from pathlib import Path

import pytest

from farrier.install import main, render_expected, set_layers


def _library(tmp_path: Path) -> Path:
    root = tmp_path / "agents"
    skill = root / "library" / "skills" / "stablemate" / "ostler" / "SKILL.md"
    skill.parent.mkdir(parents=True)
    skill.write_text(
        "---\nname: ostler\ndescription: x\n---\n\n# Ostler\n\nOstler rules.\n",
        encoding="utf-8",
    )
    prompt = root / "library" / "prompts" / "stablemate" / "commit.md"
    prompt.parent.mkdir(parents=True)
    prompt.write_text(
        "---\ndescription: Commit and push\n---\n\n# Commit\n\nPush as you go.\n",
        encoding="utf-8",
    )
    (root / "packs").mkdir()
    return root


def _repo(tmp_path: Path, mapping: str) -> Path:
    repo = tmp_path / "demo"
    repo.mkdir(parents=True, exist_ok=True)
    (repo / "agents.yml").write_text(
        "agents:\n  claude: true\n  codex: false\n"
        "skills:\n  - stablemate/ostler\n"
        "prompts:\n  - stablemate/commit\n"
        "localInstructions:\n" + mapping,
        encoding="utf-8",
    )
    return repo


def _render(tmp_path: Path, mapping: str) -> tuple[Path, dict[Path, str]]:
    root = _library(tmp_path)
    set_layers(root)
    repo = _repo(tmp_path, mapping)
    from farrier.frontmatter import read_yaml

    return repo, render_expected(read_yaml(repo / "agents.yml"), repo)


def test_prompt_body_is_aggregated_after_the_skills(tmp_path):
    repo, outputs = _render(
        tmp_path,
        "  - skills: [demo-ostler]\n"
        "    prompts: [demo-commit]\n"
        '    paths: ["."]\n'
        "    includeReadme: none\n",
    )
    body = outputs[repo / "CLAUDE.md"]
    assert body.index("Ostler rules.") < body.index("Push as you go.")
    # The prompt's own front matter never reaches the aggregated file.
    assert "description: Commit and push" not in body


def test_prompt_only_mapping_needs_no_skill(tmp_path):
    repo, outputs = _render(
        tmp_path,
        "  - prompt: demo-commit\n    paths: [\".\"]\n    includeReadme: none\n",
    )
    assert "Push as you go." in outputs[repo / "CLAUDE.md"]


def test_mapping_with_no_source_is_rejected(tmp_path):
    with pytest.raises(SystemExit) as exc:
        _render(tmp_path, '  - paths: ["."]\n')
    assert "at least one source" in str(exc.value)


def test_filename_names_the_single_output(tmp_path):
    # claude adapter only, yet the root file is AGENTS.md: that is the whole
    # point of the key — the name is not the adapter's to choose.
    repo, outputs = _render(
        tmp_path,
        "  - skill: demo-ostler\n"
        "    filename: AGENTS.md\n"
        '    paths: ["."]\n'
        "    includeReadme: none\n",
    )
    assert repo / "AGENTS.md" in outputs
    assert repo / "CLAUDE.md" not in outputs
    # Still rendered for the claude target — the banner is a Claude-only comment.
    assert "DO NOT EDIT" in outputs[repo / "AGENTS.md"]


def test_unknown_filename_is_rejected(tmp_path):
    with pytest.raises(SystemExit) as exc:
        _render(
            tmp_path,
            "  - skill: demo-ostler\n    filename: RULES.md\n    paths: [\".\"]\n",
        )
    assert "filename" in str(exc.value)


def test_source_resolves_a_filename_mapped_file_to_skill_and_prompt(tmp_path, capsys):
    root = _library(tmp_path)
    repo = _repo(
        tmp_path,
        "  - skills: [demo-ostler]\n"
        "    prompts: [demo-commit]\n"
        "    filename: AGENTS.md\n"
        '    paths: ["."]\n',
    )
    generated = repo / "AGENTS.md"
    generated.write_text("<!--\ngenerated by farrier\n-->\n\n# Body\n", encoding="utf-8")
    assert main(["source", str(generated), "--library", str(root)]) == 0
    assert capsys.readouterr().out.strip().splitlines() == [
        str((root / "library/skills/stablemate/ostler/SKILL.md").resolve()),
        str((root / "library/prompts/stablemate/commit.md").resolve()),
    ]
