"""`farrier source <generated-file>` resolves a generated skill/command back to its
editable library source path.

A generated adapter carries a machine-independent `metadata.source` (anchored at
`library/`). `farrier source` joins it under the library root resolved exactly as
`install` does, so an agent can go from a generated `.claude/skills/**/SKILL.md`
to the editable source of truth using only the file's front matter.

Aggregated local CLAUDE.md files have no front matter — their provenance lives in
the leading DO-NOT-EDIT HTML banner, which may list several sources. `farrier
source` falls back to parsing that banner and prints one editable path per line.

    ./.venv/bin/python -m pytest tests/test_source_command.py
"""
from __future__ import annotations

from pathlib import Path

import pytest

from farrier.install import frontmatter_metadata, main


def _library(tmp_path: Path) -> Path:
    """A minimal but valid library root (must contain library/ and packs/)."""
    root = tmp_path / "agents"
    src = root / "library" / "skills" / "stablemate" / "ostler" / "SKILL.md"
    src.parent.mkdir(parents=True)
    src.write_text("---\nname: ostler\n---\n\n# Ostler\n", encoding="utf-8")
    (root / "packs").mkdir()
    return root


def _generated(tmp_path: Path, source_rel: str) -> Path:
    dest = tmp_path / "repo" / ".claude" / "skills" / "stablemate-ostler" / "SKILL.md"
    dest.parent.mkdir(parents=True)
    dest.write_text(
        "---\n"
        "name: stablemate-ostler\n"
        'description: "x"\n'
        "metadata:\n"
        "  generated_by: farrier\n"
        f"  source: {source_rel}\n"
        '  resolve: "farrier source .claude/skills/stablemate-ostler/SKILL.md"\n'
        '  do_not_edit: "..."\n'
        "---\n\n# Ostler\n",
        encoding="utf-8",
    )
    return dest


def test_frontmatter_metadata_reads_nested_block(tmp_path):
    gen = _generated(tmp_path, "library/skills/stablemate/ostler/SKILL.md")
    meta = frontmatter_metadata(gen.read_text(encoding="utf-8"))
    assert meta["source"] == "library/skills/stablemate/ostler/SKILL.md"
    assert meta["generated_by"] == "farrier"


def test_frontmatter_metadata_empty_without_block(tmp_path):
    plain = tmp_path / "plain.md"
    plain.write_text("# not generated\n", encoding="utf-8")
    assert frontmatter_metadata(plain.read_text(encoding="utf-8")) == {}


def test_source_resolves_to_library_file(tmp_path, capsys):
    root = _library(tmp_path)
    gen = _generated(tmp_path, "library/skills/stablemate/ostler/SKILL.md")
    rc = main(["source", str(gen), "--library", str(root)])
    assert rc == 0
    printed = capsys.readouterr().out.strip()
    assert printed == str(
        (root / "library/skills/stablemate/ostler/SKILL.md").resolve()
    )


def test_source_errors_without_metadata(tmp_path):
    root = _library(tmp_path)
    plain = tmp_path / "plain.md"
    plain.write_text("# not generated\n", encoding="utf-8")
    with pytest.raises(SystemExit) as exc:
        main(["source", str(plain), "--library", str(root)])
    assert "metadata.source" in str(exc.value)


def _banner_generated(tmp_path: Path, source_rels: list[str]) -> Path:
    dest = tmp_path / "repo" / "svc" / "CLAUDE.md"
    dest.parent.mkdir(parents=True)
    listed = "\n".join(f"  {rel}" for rel in source_rels)
    dest.write_text(
        "<!--\n"
        "DO NOT EDIT — generated by farrier from the agent library.\n"
        "Edit the library source(s) instead, then regenerate:\n"
        f"{listed}\n"
        "Editable paths on this machine: `farrier source svc/CLAUDE.md`\n"
        "-->\n\n# Body\n",
        encoding="utf-8",
    )
    return dest


def test_source_resolves_claude_md_banner(tmp_path, capsys):
    root = _library(tmp_path)
    gen = _banner_generated(tmp_path, ["library/skills/stablemate/ostler/SKILL.md"])
    rc = main(["source", str(gen), "--library", str(root)])
    assert rc == 0
    printed = capsys.readouterr().out.strip()
    assert printed == str(
        (root / "library/skills/stablemate/ostler/SKILL.md").resolve()
    )


def test_source_prints_every_aggregated_banner_source(tmp_path, capsys):
    root = _library(tmp_path)
    other = root / "library" / "skills" / "stablemate" / "groom" / "SKILL.md"
    other.parent.mkdir(parents=True)
    other.write_text("---\nname: groom\n---\n\n# Groom\n", encoding="utf-8")
    gen = _banner_generated(
        tmp_path,
        [
            "library/skills/stablemate/ostler/SKILL.md",
            "library/skills/stablemate/groom/SKILL.md",
        ],
    )
    rc = main(["source", str(gen), "--library", str(root)])
    assert rc == 0
    lines = capsys.readouterr().out.strip().splitlines()
    assert lines == [
        str((root / "library/skills/stablemate/ostler/SKILL.md").resolve()),
        str((root / "library/skills/stablemate/groom/SKILL.md").resolve()),
    ]


def _repo_with_config(tmp_path: Path, mapped: bool) -> Path:
    repo = tmp_path / "repo"
    (repo / "svc").mkdir(parents=True, exist_ok=True)
    mapping = (
        "localInstructions:\n  - skill: demo-ostler\n    paths: [svc]\n"
        if mapped
        else ""
    )
    (repo / "agents.yml").write_text(
        "repo:\n  name: demo\n"
        "agents:\n  claude: true\n"
        "skills:\n  - stablemate/ostler\n" + mapping,
        encoding="utf-8",
    )
    return repo


def test_source_prefers_agents_yml_mapping_over_banner(tmp_path, capsys):
    # The banner is a generation-time snapshot; the live localInstructions
    # mapping must win when agents.yml is present.
    root = _library(tmp_path)
    repo = _repo_with_config(tmp_path, mapped=True)
    gen = repo / "svc" / "CLAUDE.md"
    gen.write_text(
        "<!--\nDO NOT EDIT — generated by farrier from the agent library.\n"
        "  library/skills/stale/old/SKILL.md\n-->\n\n# Body\n",
        encoding="utf-8",
    )
    rc = main(["source", str(gen), "--library", str(root)])
    assert rc == 0
    printed = capsys.readouterr().out.strip()
    assert printed == str(
        (root / "library/skills/stablemate/ostler/SKILL.md").resolve()
    )


def test_source_errors_when_mapping_removed_from_agents_yml(tmp_path):
    # agents.yml exists but no longer maps this directory: the file is stale
    # and resolving via its banner would invite edits install then discards.
    root = _library(tmp_path)
    repo = _repo_with_config(tmp_path, mapped=False)
    gen = repo / "svc" / "CLAUDE.md"
    gen.write_text(
        "<!--\nDO NOT EDIT — generated by farrier from the agent library.\n"
        "  library/skills/stablemate/ostler/SKILL.md\n-->\n\n# Body\n",
        encoding="utf-8",
    )
    with pytest.raises(SystemExit) as exc:
        main(["source", str(gen), "--library", str(root)])
    assert "stale" in str(exc.value)
    assert "localInstructions" in str(exc.value)


def test_source_banner_fallback_warns_without_agents_yml(tmp_path, capsys):
    root = _library(tmp_path)
    gen = _banner_generated(tmp_path, ["library/skills/stablemate/ostler/SKILL.md"])
    rc = main(["source", str(gen), "--library", str(root)])
    assert rc == 0
    assert "may be stale" in capsys.readouterr().err


def test_source_banner_errors_when_library_lacks_a_source(tmp_path):
    root = _library(tmp_path)
    gen = _banner_generated(tmp_path, ["library/skills/does/not/exist/SKILL.md"])
    with pytest.raises(SystemExit) as exc:
        main(["source", str(gen), "--library", str(root)])
    assert "does not exist in any library layer" in str(exc.value)


def test_source_errors_when_library_lacks_the_source(tmp_path):
    root = _library(tmp_path)
    gen = _generated(tmp_path, "library/skills/does/not/exist/SKILL.md")
    with pytest.raises(SystemExit) as exc:
        main(["source", str(gen), "--library", str(root)])
    assert "does not exist in any library layer" in str(exc.value)
