"""The PR boundary: open the epic's PR, or one PR per repo in story mode."""
from __future__ import annotations

import logging
from pathlib import Path

from github import GithubException
from ostler import markdown, path as okf_path, registry
from workhorse_workflows.coder.shared.plan import get_affected_repos, load_plan_context
from workhorse_workflows.kit import find_repo_root
from workhorse_workflows.coder.shared import commits, paths
from workhorse_workflows.coder.shared.blueprint import blueprint
from workhorse_workflows.coder.shared.branches import epic_branch
from workhorse_workflows.coder.shared.ci import push_epic_branch
from workhorse_workflows.coder.shared.schemas.pr import (
    PrGate,
    StoryPr,
)
from workhorse_workflows.kit import (
    branch_exists,
    checkout,
    commit_all,
    commit_paths,
    current_branch,
    find_open_pr,
    get_repo_config,
    origin_url,
    push_branch,
    resolve_github_token,
    resolve_repo,
    resolve_workspace,
)

SCREENSHOT_SUFFIXES = (".png", ".jpg", ".jpeg", ".gif")

PLAN_SUMMARY_HEADING = "1. Summary"



@blueprint.node
def open_pr(
    logger: logging.Logger,
    epic: str = "",
    base_branch: str = "main",
    repo_dir: str = "",
) -> PrGate:
    """Open the finished epic's PR, and say whether there is anything to gate CI on."""
    if not epic:
        logger.info("no epic — nothing to PR")
        return PrGate(ci_base=base_branch)

    root = find_repo_root(repo_dir)
    branch = epic_branch(epic)
    _commit_queue_prune(logger, root, epic, branch)

    _open_epic_pr(logger, epic, base_branch, repo_dir)
    return PrGate(should_gate=True, ci_epic=epic, ci_base=base_branch)


def _commit_queue_prune(logger: logging.Logger, root: Path, epic: str, branch: str) -> None:
    """Commit the queue prune onto the epic branch, best-effort."""
    if not branch_exists(root, branch):
        return
    prune = commits.message(
        "chore",
        commits.scope(root.name),
        "prune completed epic from queue",
        epic=epic,
    )
    if commit_paths(root, prune, paths.epics_index(root)):
        logger.info("committed index.md prune onto %s", branch)


def _epic_pr_title(root: Path, epic: str) -> str:
    """The epic PR's title: a Conventional Commit subject, because a squash merge makes it one."""
    name = registry.epic_slug(epic) or epic
    try:
        epic_md = okf_path.epic_dir_in(root, epic) / "epic.md"
        description = commits.story_description(root, str(epic_md.relative_to(root)), name)
    except (OSError, ValueError, RuntimeError):
        description = commits.describe(name)
    return commits.subject("feat", commits.scope(root.name), description)


def _open_epic_pr(logger: logging.Logger, epic: str, base: str, repo_dir: str = "") -> None:
    """Push the epic branch and open its PR."""
    branch = epic_branch(epic)
    root = find_repo_root(repo_dir)

    if not branch_exists(root, branch):
        logger.info("no branch %s to PR", branch)
        return

    token = resolve_github_token(root)
    if not token:
        logger.info(
            "no GitHub token (set workflow.githubTokenEnv in agents.yml) — "
            "leaving %s for a manual PR",
            branch,
        )
        return
    if not origin_url(root):
        logger.info("no 'origin' remote — leaving %s for a manual PR", branch)
        return

    repo, slug = resolve_repo(root, token)
    if repo is None:
        logger.info(
            "origin is not a reachable github.com repo (%s) — leaving %s for a manual PR",
            slug, branch,
        )
        return

    push_epic_branch(logger, root, branch)

    if find_open_pr(repo, branch) is not None:
        logger.info("PR already open for %s", branch)
        return

    try:
        repo.create_pull(
            base=base,
            head=branch,
            title=_epic_pr_title(root, epic),
            body=(
                f"Automated epic PR for `{epic}`, generated by the coder workflow. "
                "One PR per epic; one commit per completed story.\n\n"
                "The title is a Conventional Commit subject on purpose: a squash merge "
                "makes it the only line release-please reads for this epic."
            ),
        )
    except Exception as exc:  # noqa: BLE001 - an unopened PR is a manual follow-up, not a failure
        logger.info("PR create failed for %s: %s", branch, exc)


@blueprint.node
def open_story_pr(
    logger: logging.Logger,
    story_slug: str = "",
    base_branch: str = "main",
    story_path: str = "",
    spec_dir: str = "",
    story_branch: str = "",
    repo_dir: str = "",
    workspace_file: str = "",
) -> StoryPr:
    """Story mode's terminal: one PR per affected **code** repo, none in the docs repo."""
    if not story_slug:
        logger.info("no story slug — nothing to PR")
        return StoryPr()

    branch = story_branch or story_slug
    root = find_repo_root(repo_dir)
    repos = resolve_workspace(workspace_file, repo_dir)

    spec = root / spec_dir if spec_dir else None
    plan_ctx = load_plan_context(root, spec_dir, logger)
    affected = get_affected_repos(plan_ctx, repos)
    if not affected:
        logger.info("no affected repos resolved — nothing to PR")
        return StoryPr()

    description = commits.story_description(root, story_path, story_slug)
    summary = _plan_summary_prose(spec) if spec else ""
    screenshots = _qa_screenshots(root, story_path)

    token = resolve_github_token(root)
    if not token:
        logger.info("no GitHub token — leaving %s for manual PRs", branch)
        return StoryPr()

    results: list[str] = []
    pr_urls: list[str] = []
    for name in affected:
        info = repos.get(name, {})
        repo_path = Path(info.get("path", ""))
        if not repo_path.is_dir():
            logger.warning("repo %s path not found: %s", name, repo_path)
            results.append("skipped")
            continue
        if not (repo_path / ".git").exists():
            logger.warning("repo %s is not a git repo — skipping", name)
            results.append("skipped")
            continue

        repo_base = _repo_base_branch(repo_path, name, repos)
        title = commits.subject("feat", commits.scope(name), description)
        _commit_in_repo(
            logger,
            repo_path,
            branch,
            commits.message("feat", commits.scope(name), description, story=story_slug),
        )

        body = _pr_body(summary, screenshots)
        result, pr_url = _push_and_pr(logger, repo_path, branch, repo_base, title, body, token)
        results.append(result)
        if result in ("opened", "exists") and pr_url:
            pr_urls.append(pr_url)

    if "opened" in results:
        status = "opened"
    elif "exists" in results:
        status = "exists"
    else:
        status = "skipped"

    return StoryPr(story_pr=status, pr_urls=pr_urls)


def _plan_summary_prose(spec_dir: Path) -> str:
    """The plan's `## 1."""
    plan_file = spec_dir / "plan.md"
    if not plan_file.exists():
        return ""
    try:
        text = plan_file.read_text(encoding="utf-8")
    except OSError:
        return ""
    section = markdown.split(text).find_section(PLAN_SUMMARY_HEADING)
    if section is None:
        return ""
    paragraphs = [p.strip() for p in section.body.strip().split("\n\n") if p.strip()]
    return "\n\n".join(paragraphs[:2])


def _qa_screenshots(root: Path, story_path: str) -> list[str]:
    """The images under the story's `qa/` dir, repo-relative."""
    if not story_path:
        return []
    qa_dir = root / Path(story_path).parent / "qa"
    if not qa_dir.is_dir():
        return []
    return [
        str(f.relative_to(root))
        for f in sorted(qa_dir.rglob("*"))
        if f.suffix.lower() in SCREENSHOT_SUFFIXES
    ]


def _pr_body(summary: str, screenshots: list[str]) -> str:
    """The PR description: the plan summary, the QA evidence, and the provenance note."""
    parts = []
    if summary:
        parts.append(f"## Summary\n\n{summary}")
    if screenshots:
        parts.append("## QA Evidence\n")
        parts.append("Screenshots captured during QA (in the docs repo `qa/` dir):\n")
        for shot in screenshots[:6]:
            name = Path(shot).stem.replace("-", " ").replace("_", " ")
            parts.append(f"- `{shot}` — {name}")
    parts.append(
        "\n---\n*Automated story PR generated by the coder workflow (story mode). "
        "Left open for review — not auto-merged.*"
    )
    return "\n\n".join(parts)


def _repo_base_branch(repo_path: Path, name: str, repos: dict, fallback: str = "main") -> str:
    """The repo's declared base branch, else the first of develop/main/master it has."""
    declared = get_repo_config(name, "base_branch", repos=repos)
    if declared:
        return declared
    for candidate in ("develop", "main", "master"):
        if branch_exists(repo_path, candidate):
            return candidate
    return fallback


def _commit_in_repo(logger: logging.Logger, repo_path: Path, branch: str, message: str) -> None:
    """Commit whatever is pending in a code repo, on the story branch."""
    if current_branch(repo_path) != branch and not (
        checkout(repo_path, branch) or checkout(repo_path, branch, create=True)
    ):
        logger.warning("cannot checkout %s in %s", branch, repo_path.name)
        return
    commit_all(repo_path, message)


def _push_and_pr(
    logger: logging.Logger,
    repo_path: Path,
    branch: str,
    base: str,
    title: str,
    body: str,
    token: str,
) -> tuple[str, str]:
    """Push one repo's story branch and open its PR: `(opened|exists|skipped, url)`."""
    if not branch_exists(repo_path, branch):
        logger.warning("no branch %s in %s", branch, repo_path.name)
        return "skipped", ""

    gh_repo, slug = resolve_repo(repo_path, token)
    if gh_repo is None:
        logger.warning(
            "%s: origin %s not a reachable github.com repo — skipping", repo_path.name, slug
        )
        return "skipped", ""

    if not push_branch(repo_path, token, branch, verify=False):
        logger.warning("push failed for %s in %s", branch, repo_path.name)
        return "skipped", ""

    existing = find_open_pr(gh_repo, branch)
    if existing is not None:
        logger.info("PR already open for %s in %s", branch, repo_path.name)
        return "exists", existing.html_url

    try:
        pr = gh_repo.create_pull(base=base, head=branch, title=title, body=body)
    except GithubException as exc:
        logger.warning("PR create failed in %s: %s", repo_path.name, exc)
        return "skipped", ""

    logger.info("opened PR for %s → %s in %s", branch, base, repo_path.name)
    return "opened", pr.html_url


__all__ = [
    "open_pr",
    "open_story_pr",
]
