"""The process boundary a paddock task drives stablemate across."""

from __future__ import annotations

import subprocess
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

from paddock import Run, project
from stablemate_core import config as core_config


class TrialError(RuntimeError):
    """A fixture or trial precondition that fails before anything has been measured."""


def git(*args: str, cwd: Path) -> str:
    proc = subprocess.run(
        ["git", *args], cwd=str(cwd), capture_output=True, text=True, check=False
    )
    if proc.returncode != 0:
        raise TrialError(f"git {' '.join(args)} in {cwd}: {proc.stderr.strip()}")
    return proc.stdout


def _describe(checkout: Path) -> list[str]:
    """What the toolchain looks like right now: its `git status --porcelain` lines, and the commit it is sitting on."""
    stashed = project.stashed_git_dir(checkout)
    where = ["--git-dir", str(stashed), "--work-tree", str(checkout)] if stashed.is_dir() else []
    lines = [line for line in git(*where, "status", "--porcelain", cwd=checkout).splitlines() if line]
    head = git(*where, "rev-parse", "HEAD", cwd=checkout).strip()
    return [*lines, f"committed — HEAD is now {head}"]


def pin_held(pin: project.Project | None) -> bool:
    """Whether a round got the pin it was configured for — not merely asked for one."""
    return pin is not None and pin.pinned


@contextmanager
def no_leaks(checkout: Path, *, pinned: bool) -> Iterator[None]:
    """Fail the round if the toolchain checkout changed while it ran."""
    before = set(_describe(checkout))
    yield
    leaked = sorted(set(_describe(checkout)) - before)
    if not leaked:
        return
    if pinned:
        raise TrialError(
            f"the round wrote into {checkout} instead of its sandboxes:\n"
            + "\n".join(leaked)
            + "\nrevert that before believing any number here"
        )
    raise TrialError(
        f"{checkout} changed while the round ran, and this round was not pinned — so "
        f"whether the round wrote this or somebody else did is not knowable from here:\n"
        + "\n".join(leaked)
        + "\nre-run pinned before believing any number here"
    )


def stablemate_dir() -> Path:
    """The stablemate checkout the trials drive `workhorse-coder` out of."""
    resolved = core_config.resolve_stablemate_dir()
    if resolved is None or not (resolved / "pyproject.toml").is_file():
        raise TrialError(
            "no `stablemate_dir` in the machine's stablemate config — the trials need a "
            "checkout to run `workhorse-coder` out of (set it with `farrier config`)"
        )
    return resolved


def stablemate_checkout(run: Run) -> Path:
    """The checkout *this run* drives, which is not always the operator's."""
    project = run.project
    if project is not None and (project / "pyproject.toml").is_file():
        return project
    return stablemate_dir()


def uv_run(checkout: Path, package: str) -> list[str]:
    """The `uv run` prefix that runs *checkout*'s own code, not this machine's."""
    return ["uv", "run", "--project", str(checkout), "--package", package]


def effective(run: Run) -> Path:
    return run.scratch / "stablemate-config.toml"


def pin_config(run: Run) -> None:
    """Write the effective stablemate config the trials run under, into `scratch/`."""
    machine = core_config.load_config()
    local = {
        name: str(value)
        for name in ("library_dir", "base_dir", "stablemate_dir", "worktree_dir")
        if isinstance(value := core_config.get_config_value(name, machine), str) and value
    }
    local["stablemate_dir"] = str(stablemate_checkout(run))
    if "library_dir" not in local:
        raise TrialError(
            "no `library_dir` in the machine's stablemate config — a run given --config "
            "inherits nothing from the machine's, so the library root has to come from here"
        )
    header = (
        "# Generated by a paddock task. The model tables come from the tracked\n"
        "# config; the paths below are this machine's and are why this file is not tracked.\n"
    )
    rendered = "\n".join(f'{name} = "{path}"' for name, path in sorted(local.items()))
    effective(run).write_text(
        f"{header}{rendered}\n\n{run.config.read_text(encoding='utf-8')}", encoding="utf-8"
    )
