#!/usr/bin/env python3
"""Push an epic branch and open its PR, authenticating to GitHub with a token.

Args: <epic> [<base_branch>=main]

Best-effort throughout: writes only to stderr and always exits 0 (this must
never halt open-pr.py, whose JSON on stdout gates the CI/merge loop). Leaves
the branch unpushed / PR unopened for a manual follow-up on any failure.
"""
from __future__ import annotations

import logging
import os
import subprocess
import sys
from pathlib import Path

from workhorse.scriptutil import (
    branch_exists,
    commit_paths,
    find_open_pr,
    find_repo_root,
    origin_url,
    resolve_github_token,
    resolve_repo,
)

QUEUE_PATH = "docs/epics/index.md"


def main(logger: logging.Logger) -> None:
    epic = sys.argv[1] if len(sys.argv) > 1 else ""
    base = sys.argv[2] if len(sys.argv) > 2 else "main"
    if not epic:
        return
    br = f"feat/{epic}"

    root = find_repo_root()
    scripts_dir = Path(__file__).resolve().parent

    if not branch_exists(root, br):
        logger.info("no branch %s to PR", br)
        return

    # Commit the queue prune onto the epic branch before pushing, best-effort.
    if commit_paths(root, f"{epic}: prune completed epic from queue", QUEUE_PATH):
        logger.info("committed index.md prune onto %s", br)

    token = resolve_github_token(root)
    if not token:
        logger.info("no GitHub token (set workflow.githubTokenEnv in agents.yml) — leaving %s for a manual PR", br)
        return
    if not origin_url(root):
        logger.info("no 'origin' remote — leaving %s for a manual PR", br)
        return

    repo, slug = resolve_repo(root, token)
    if repo is None:
        logger.info("origin is not a reachable github.com repo (%s) — leaving %s for a manual PR", slug, br)
        return

    env = {**os.environ, "GH_TOKEN": token}

    subprocess.run(
        [sys.executable, str(scripts_dir / "push-epic.py"), br],
        cwd=str(root), env=env, capture_output=True, text=True, check=False,
    )

    if find_open_pr(repo, br) is not None:
        logger.info("PR already open for %s", br)
        return

    try:
        repo.create_pull(
            base=base, head=br,
            title=f"Epic: {epic}",
            body=(
                f"Automated epic PR for `{epic}`, generated by the coder workflow. "
                "One PR per epic; one commit per completed story."
            ),
        )
    except Exception as exc:
        logger.info("PR create failed for %s: %s", br, exc)


if __name__ == "__main__":
    logging.basicConfig(stream=sys.stderr, level=logging.INFO, format="%(name)s %(levelname)s: %(message)s")
    main(logging.getLogger("gh-open-pr"))
