#!/usr/bin/env python3
"""Push story branches and open PRs in each affected code repo.

Story mode terminal: after QA passes, this script opens one PR per affected
code repo (api-service, web-app, mobile-app, …) — NOT in the docs repo (vigilant-octo).
Each PR carries:
  - Title: the story heading from story.md (e.g. "[CASE-4203] Escalation Tree - Lock…")
  - Body: the plan summary + QA evidence screenshots (for UI repos)

Best-effort: failures are logged to stderr, never halt the run. The script
always exits 0 and emits valid JSON.

Args: <story_slug> <base_branch> <story_path> <spec_dir> [<story_branch>]

<story_branch> comes from branch_story; when absent the slug is used (the branch
name and the story id are the same thing today, but the branch is branch_story's
to name, not this script's to guess).
Outputs JSON: {"story_pr": "opened|exists|skipped", "pr_urls": [...]}
"""
from __future__ import annotations

import json
import logging
import re
import sys
from pathlib import Path

from github import GithubException

from workhorse.scriptutil import (
    branch_exists,
    checkout,
    commit_all,
    current_branch,
    find_open_pr,
    find_repo_root,
    get_affected_repos,
    get_repo_config,
    load_json,
    push_branch,
    resolve_github_token,
    resolve_repo,
    resolve_workspace,
)

logger = logging.getLogger(__name__)


def read_story_title(root: Path, story_path: str) -> str:
    """Extract the first # heading from story.md as the PR title."""
    full = root / story_path if story_path else None
    if not full or not full.exists():
        return ""
    try:
        for line in full.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("# "):
                return line[2:].strip()
    except OSError:
        pass
    return ""


def read_plan_summary(spec_dir: Path) -> str:
    """Extract the ## 1. Summary section from plan.md."""
    plan_file = spec_dir / "plan.md"
    if not plan_file.exists():
        return ""
    try:
        text = plan_file.read_text(encoding="utf-8")
    except OSError:
        return ""
    # Extract from "## 1. Summary" to the next "## "
    match = re.search(r"^## 1\. Summary\s*\n(.*?)(?=\n## |\Z)", text, re.DOTALL | re.MULTILINE)
    if match:
        summary = match.group(1).strip()
        # Trim to first 2 paragraphs for brevity
        paragraphs = [p.strip() for p in summary.split("\n\n") if p.strip()]
        return "\n\n".join(paragraphs[:2])
    return ""


def find_qa_screenshots(root: Path, story_path: str) -> list[str]:
    """Find .png/.jpg files in the story's qa/ dir."""
    if not story_path:
        return []
    story_dir = root / Path(story_path).parent
    qa_dir = story_dir / "qa"
    if not qa_dir.is_dir():
        return []
    screenshots = []
    for f in sorted(qa_dir.rglob("*")):
        if f.suffix.lower() in (".png", ".jpg", ".jpeg", ".gif"):
            screenshots.append(str(f.relative_to(root)))
    return screenshots


def is_ui_repo(repo_info: dict) -> bool:
    """Check if a repo is a UI repo (playwright/maestro QA mode)."""
    qa_mode = repo_info.get("qa_mode", "")
    return qa_mode in ("playwright", "maestro")


def build_pr_body(summary: str, screenshots: list[str], repo_name: str, is_ui: bool) -> str:
    """Build the PR description."""
    parts = []
    if summary:
        parts.append(f"## Summary\n\n{summary}")
    if is_ui and screenshots:
        parts.append("## QA Evidence\n")
        parts.append("Screenshots captured during QA (in the docs repo `qa/` dir):\n")
        for s in screenshots[:6]:
            name = Path(s).stem.replace("-", " ").replace("_", " ")
            parts.append(f"- `{s}` — {name}")
    parts.append("\n---\n*Automated story PR generated by the coder workflow (story mode). Left open for review — not auto-merged.*")
    return "\n\n".join(parts)


def push_and_pr(
    repo_path: Path,
    branch: str,
    base: str,
    title: str,
    body: str,
    token: str,
) -> tuple[str, str]:
    """Push branch and open PR in a single repo. Returns (status, pr_url) where
    status is opened|exists|skipped."""
    if not branch_exists(repo_path, branch):
        logger.warning("no branch %s in %s", branch, repo_path.name)
        return "skipped", ""

    gh_repo, slug = resolve_repo(repo_path, token)
    if gh_repo is None:
        logger.warning("%s: origin %s not a reachable github.com repo — skipping", repo_path.name, slug)
        return "skipped", ""

    if not push_branch(repo_path, token, branch, verify=False):
        logger.warning("push failed for %s in %s", branch, repo_path.name)
        return "skipped", ""

    existing = find_open_pr(gh_repo, branch)
    if existing is not None:
        logger.info("PR already open for %s in %s", branch, repo_path.name)
        return "exists", existing.html_url

    try:
        pr = gh_repo.create_pull(base=base, head=branch, title=title, body=body)
    except GithubException as exc:
        logger.warning("PR create failed in %s: %s", repo_path.name, exc)
        return "skipped", ""

    logger.info("opened PR for %s → %s in %s", branch, base, repo_path.name)
    return "opened", pr.html_url


def get_repo_base_branch(repo_path: Path, repo_name: str, repos: dict, fallback: str = "main") -> str:
    """Resolve the repo's default branch from config, then git probe as fallback."""
    declared = get_repo_config(repo_name, "base_branch", repos=repos)
    if declared:
        return declared
    for candidate in ("develop", "main", "master"):
        if branch_exists(repo_path, candidate):
            return candidate
    return fallback


def commit_story_in_repo(repo_path: Path, branch: str, title: str) -> None:
    """Commit any uncommitted changes in a code repo on the story branch."""
    if current_branch(repo_path) != branch:
        # Check out the branch, creating it from the current HEAD if it doesn't exist.
        if not checkout(repo_path, branch) and not checkout(repo_path, branch, create=True):
            logger.warning("cannot checkout %s in %s", branch, repo_path.name)
            return
    # A False here just means "nothing staged" — the branch may already carry the
    # story's commits ahead of base, which is fine; not an error worth surfacing.
    commit_all(repo_path, title)


def main(logger: logging.Logger) -> None:
    slug = sys.argv[1] if len(sys.argv) > 1 else ""
    base = sys.argv[2] if len(sys.argv) > 2 else "main"
    story_path = sys.argv[3] if len(sys.argv) > 3 else ""
    spec_dir_rel = sys.argv[4] if len(sys.argv) > 4 else ""
    story_branch = sys.argv[5] if len(sys.argv) > 5 else ""

    if not slug:
        logger.info("no story slug — nothing to PR")
        print(json.dumps({"story_pr": "skipped", "pr_urls": []}))
        return

    # Consume branch_story's branch rather than re-deriving it from the slug: the
    # two drifted once already (this script kept a `story/` prefix after
    # branch-story.py dropped it, so every PR targeted a branch that was never
    # cut). Falls back to the slug for a standalone/hand invocation with no
    # branch_story output to read.
    branch = story_branch or slug
    base = base or "main"

    root = find_repo_root()
    repos = resolve_workspace("CODER_WORKSPACE")

    # Resolve affected repos from plan-context.json
    spec_dir = root / spec_dir_rel if spec_dir_rel else None
    plan_ctx = load_json(spec_dir / "plan-context.json", "plan-context.json", logger) if spec_dir and spec_dir.exists() else {}
    affected_names = get_affected_repos(plan_ctx, repos)

    if not affected_names:
        logger.info("no affected repos resolved — nothing to PR")
        print(json.dumps({"story_pr": "skipped", "pr_urls": []}))
        return

    # Read story title for PR title
    title = read_story_title(root, story_path)
    if not title:
        title = f"Story: {slug}"

    # Read plan summary for PR body
    summary = read_plan_summary(spec_dir) if spec_dir else ""
    screenshots = find_qa_screenshots(root, story_path)

    token = resolve_github_token(root)
    if not token:
        logger.info("no GitHub token — leaving %s for manual PRs", branch)
        print(json.dumps({"story_pr": "skipped", "pr_urls": []}))
        return

    # Open PRs in each affected code repo
    results = []
    pr_urls: list[str] = []
    for name in affected_names:
        repo_info = repos.get(name, {})
        repo_path = Path(repo_info.get("path", ""))
        if not repo_path.is_dir():
            logger.warning("repo %s path not found: %s", name, repo_path)
            results.append("skipped")
            continue

        # Check if repo is a git repo
        if not (repo_path / ".git").exists():
            logger.warning("repo %s is not a git repo — skipping", name)
            results.append("skipped")
            continue

        # Detect the repo's own default branch (not vigilant-octo's)
        repo_base = get_repo_base_branch(repo_path, name, repos)

        # Commit any pending changes
        commit_story_in_repo(repo_path, branch, title)

        # Build PR body tailored to this repo
        body = build_pr_body(summary, screenshots, name, is_ui_repo(repo_info))

        result, pr_url = push_and_pr(repo_path, branch, repo_base, title, body, token)
        results.append(result)
        if result in ("opened", "exists") and pr_url:
            pr_urls.append(pr_url)

    # Overall status: best result wins
    if "opened" in results:
        status = "opened"
    elif "exists" in results:
        status = "exists"
    else:
        status = "skipped"

    print(json.dumps({"story_pr": status, "pr_urls": pr_urls}))


if __name__ == "__main__":
    # workhorse imports this and calls main(logger) itself; this guard is only for
    # running the script by hand.
    logging.basicConfig(stream=sys.stderr, level=logging.INFO, format="[open-story-pr] %(message)s")
    main(logging.getLogger("open-story-pr"))
